### ISSUE TITLE
Unable to install stripe_payment version 0.0.4

### ISSUE THREAD

**Issue by Aman-US-Punjabi** [jonasbark/flutter_stripe_payment#1]
Error:
Package stripe_payment has no versions that match >=0.0.4 <0.1.0 derived from:
- demoapp depends on version ^0.0.4
pub get failed (1)
exit code 1

**Comment by jonasbark** [comment]
are you trying to use Dart 2? Can you provide more details about your project configuration?

**Comment by jonasbark** [comment]
Fixed with 0.0.5.
