### ISSUE TITLE
Package Support For Dart > 2.0.0

### ISSUE THREAD

**Issue by wesharper** [jonasbark/flutter_stripe_payment#10]
This package doesn't work with Dart version 2.1.0

**Comment by jonasbark** [comment]
What error are you getting? Dart 2.1.0 is supported.

I updated the plugin to 0.0.7 to support newer Kotlin version. Does this work for you?

**Comment by jonasbark** [comment]
Closing this as it the main issue is unrelated. Let me know if it doesn't work for you.
