### ISSUE TITLE
use in minsdk 16 project

### ISSUE THREAD

**Issue by Shubham-8197** [jonasbark/flutter_stripe_payment#100]
So now my all whole projects minsdk version is 16 if i'm upgread it to 19 then my project will be collapsed. So in this situation how can i use stripe_payment ??

**Comment by driveweyus** [comment]
Same issue any help?

**Comment by jonasbark** [comment]
You could override the minSdk for this library:
https://stackoverflow.com/questions/27335889/how-do-i-ignore-minsdkversion-of-library-in-android-studio
But you have to make sure that stripe_package functions aren't called for Android lower than Level 19. 
The Stripe dependency has a minimum API level set to 19: 
https://github.com/stripe/stripe-android/blob/master/stripe/build.gradle#L58

There's nothing we can do about that.
