### ISSUE TITLE
Still need to add certificate through stripe?

### ISSUE THREAD

**Issue by Marcusg62** [jonasbark/flutter_stripe_payment#103]
Hi, 
I am having a similar issue on iOS as described here. https://github.com/jonasbark/flutter_stripe_payment/issues/102

I am wondering if I am missing a step. To work with apple pay, do you still need to add the application through the Stripe Dashboard as referenced in version 0.3.1? https://pub.flutter-io.cn/packages/stripe_native

**Comment by Marcusg62** [comment]
Yes, you do. Also, there we made a silly mistake in the setOptions function where we kept the code from example with `merchantID: 'Test'`. This needs to be the merchant ID generated when setting up Apple Pay in Xcode. 
Also, is it possible to change that to `merchantID: 'INSERT YOUR MERCHANT ID HERE'` or something like that? It would have saved a few hours of confusion. :)

**Comment by jonasbark** [comment]
Feel free to make a pull request 👍

**Comment by ldemyanenko** [comment]
I had the same issue. It wasn't obvious setup step
