### ISSUE TITLE
How to disable snackbar popups?

### ISSUE THREAD

**Issue by Marcusg62** [jonasbark/flutter_stripe_payment#108]
Hi, sorry for such a trivial question but I've been through all the documentation and can't figure out how to disable to snackbar popups. How do I do that?
Thanks!

**Comment by jonasbark** [comment]
Which popups do you mean?

**Comment by Waqas08** [comment]
e: C:\Users\WAQAS\AppData\Local\Flutter\.pub-cache\hosted\pub.dartlang.org\stripe_payment-1.0.6\android\src\m
ain\kotlin\de\jonasbark\stripepayment\StripeDialog.kt: (6, 36): Unresolved reference: snackbar
e: C:\Users\WAQAS\AppData\Local\Flutter\.pub-cache\hosted\pub.dartlang.org\stripe_payment-1.0.6\android\src\m
ain\kotlin\de\jonasbark\stripepayment\StripeDialog.kt: (98, 33): Unresolved reference: Snackbar
e: C:\Users\WAQAS\AppData\Local\Flutter\.pub-cache\hosted\pub.dartlang.org\stripe_payment-1.0.6\android\src\m
ain\kotlin\de\jonasbark\stripepayment\StripeDialog.kt: (98, 75): Unresolved reference: Snackbar
e: C:\Users\WAQAS\AppData\Local\Flutter\.pub-cache\hosted\pub.dartlang.org\stripe_payment-1.0.6\android\src\m
ain\kotlin\de\jonasbark\stripepayment\StripeDialog.kt: (108, 17): Unresolved reference: Snackbar
e: C:\Users\WAQAS\AppData\Local\Flutter\.pub-cache\hosted\pub.dartlang.org\stripe_payment-1.0.6\android\src\m
ain\kotlin\de\jonasbark\stripepayment\StripeDialog.kt: (108, 79): Unresolved reference: Snackbar

**Comment by Waqas08** [comment]
What are these problems when compling a release build.

**Comment by Marcusg62** [comment]
> Hi, sorry for such a trivial question but I've been through all the documentation and can't figure out how to disable to snackbar popups. How do I do that?
> Thanks!

The try catch block in the example has built in functions which sends the responses to a snackbar. I simply commented out those lines of code.
