### ISSUE TITLE
Way to send user email to stripe?

### ISSUE THREAD

**Issue by jellyNoone** [jonasbark/flutter_stripe_payment#111]
Hi, I've been trying to implement your plugin, but I cant seem to find a way to send the email address with the .paymentRequestWithCardForm. The CardFormPaymentRequest does have field for prefield information, but this is the billing address, not the phone number and the email address you can send to stripe with the tipsi-stripe plugin or the stripe api. How could I send the email to stripe using your plugin?

**Comment by macmatrix** [comment]
You can send the email from the client to the server and from the server you can send the email address to stripe. That email address will receive the receipt of the transaction once the transaction is successful

**Comment by jellyNoone** [comment]
Ok, thank you!
