### ISSUE TITLE
CardFormPaymentRequest amount

### ISSUE THREAD

**Issue by monish152** [jonasbark/flutter_stripe_payment#112]
I just checked this package. I am trying to make payment locally. I think CardFormPaymentRequest works for this. But there is no way to send payment amount. Please let me know how I can add this parameter. 

Or how I can make payment without help of backend.

**Comment by nicowernli** [comment]
You can't do a complete payment without backend. This is not a plugin limitation, it is how stripe works for security reasons. Please read stripe documentation on how to perform payments https://stripe.com/docs/payments/accept-a-payment

**Comment by monish152** [comment]
ok Thanks @nicowernli  but as I can see after getting token we can make payment. I checked sample there is no sample for this. Can you please help in that.

**Comment by nicowernli** [comment]
No, you have to create your PaymentIntent in your backend as it says in Stripe documentation

**Comment by monish152** [comment]
ok, I am using same js file without any change and after deploy I am getting these error.
<img width="808" alt="Screenshot 2020-01-10 at 12 17 00 AM" src="https://user-images.githubusercontent.com/1301491/72095565-b66ff180-333e-11ea-9d82-bf77748c5671.png">

**Comment by monish152** [comment]
from app I am getting payment method id how I can use that in backend to charge payment. Can you please provide link so I can pass to developer.
