### ISSUE TITLE
How could I store CreditCard instance?

### ISSUE THREAD

**Issue by XinwenCheng** [jonasbark/flutter_stripe_payment#122]
Hi,

I have a question and I hope someone familiar with this plug in could give me some detailed suggestion.

I call <code>StripePayment.paymentRequestWithCardForm(CardFormPaymentRequest())</code> and prebuilt Credit Card UI pops up, then I can input my credit card number, expire month and year and CVV, and this function will return summarized credit card data through then() function such as following:
```json
{
    "addressLine1": null,
    "addressLine2": null,
    "brand": "visa",
    "country": "US",
    "expMonth": 7,
    "expYear": 2020,
    "funding": "credit",
    "last4": "4242"
}
```

It has no card number. I store it as I want to call <code>StripePayment.createPaymentMethod(            PaymentMethodRequest(card: creditCard))</code> to create a payment method and start payment.

My question is how could I get and store a full credit card data and make user payment easy and quick?

Thanks in advance!

**Comment by nicowernli** [comment]
You can't get and store by yourself a full credit card. What you have to do is using the payment method id that stripe gives you to complete the purchase.
Stripe has a very clear and complete documentation, [take a look here](https://stripe.com/docs/saving-cards).

**Comment by XinwenCheng** [comment]
Sure, thanks @nicowernli !
