### ISSUE TITLE
Fails to start on android

### ISSUE THREAD

**Issue by dwarakanathchandu** [jonasbark/flutter_stripe_payment#13]
Hi,

I tried to run my flutter app and it crashes at start up. I am using Flutter 1.0.0 .
I added **classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.10"** to root level build.gradle file.
Please let me know if you need more info.

Thanks,
Chandu

**Comment by jonasbark** [comment]
1. What crash exactly?
2. did you follow the Android part in the readme?

`Please be aware that your main activity must extend from FlutterFragmentActivity. Otherwise the Android dialog would've looked very nasty.`

**Comment by dwarakanathchandu** [comment]
Hi jonasbark,
Thanks for the response.
I am using flutter 1.0.0 and added **stripe_payment: ^0.0.8 in pubspec.yaml file** and used **flutter packages get command.** 
I used flutter run command to run on android device.
It builds successfully and when tries to launch on the device it is closing immediately. 

sorry for the confusion i'm not using main activity or native android sdk.

Thanks,
Chandu

**Comment by jonasbark** [comment]
Go into the Android part of your flutter project, find the Activity (possibly called MainActivity). You have to extend this class from FlutterFragmentActivity. Please have a look at the example application to verify. 

I'm closing this as the crash issue is clear.
