### ISSUE TITLE
Use CardInputWidget instead of StripeDialog to display credit card input form

### ISSUE THREAD

**Issue by philiplindberg** [jonasbark/flutter_stripe_payment#132]
The latest version of the Stripe Android SDK (v14.2) recommends displaying the credit card input form as a `CardInputWidget`.

Here's how the credit card input form is currently being displayed on Android:

<img src="https://user-images.githubusercontent.com/1865904/77545859-f6a53180-6ea2-11ea-9304-07e04ef1daff.png" width="375" />

And here's the new and improved `CardInputWidget` from the latest Android SDK:

<img src="https://user-images.githubusercontent.com/1865904/77545875-fb69e580-6ea2-11ea-8b8d-f1b22e78c652.gif" width="375" />

Are there any plans to upgrade the Stripe Android SDK and use the `CardInputWidget`? Happy to submit a PR for this if needed.

**Comment by ened** [comment]
I had a go at this as well - the problem is quite deep in the Flutter framework in regard to input handling https://github.com/flutter/flutter/wiki/Android-Platform-Views#text-input

Perhaps this is a candidate for a native "Flutter widget".

**Comment by jonasbark** [comment]
There are quite a few promising Flutter packages regarding Credit Card input already out there

**Comment by philiplindberg** [comment]
@jonasbark Any plans to upgrade the android credit card input form in the near future? If so, is this something you need help with?

**Comment by jonasbark** [comment]
I'm happy to accept pull requests but I don't plan on getting involved regarding that.
