### ISSUE TITLE
Create the payment only in flutter

### ISSUE THREAD

**Issue by fipooo** [jonasbark/flutter_stripe_payment#136]
It's possible to create the full payment only in dart? Simple payment only with google pay or apple pay.  I create all app flutter + firebase and now I need to add the payment to complete the registration. I don't need to save any information in database. I found few tutorial but they was to old and they doesn't worked.

**Comment by mario202k** [comment]
![image](https://user-images.githubusercontent.com/18236718/77770508-c86c5100-705e-11ea-8b17-8e10e220f1ae.png)

Your flutter app should interact like this

**Comment by fipooo** [comment]
> ![image](https://user-images.githubusercontent.com/18236718/77770508-c86c5100-705e-11ea-8b17-8e10e220f1ae.png)
> 
> Your flutter app should interact like this

Like here yes? https://medium.com/@info_4766/build-a-marketplace-in-your-flutter-app-and-accept-payments-using-stripe-and-firebase-59f074201718

**Comment by mario202k** [comment]
> > ![image](https://user-images.githubusercontent.com/18236718/77770508-c86c5100-705e-11ea-8b17-8e10e220f1ae.png)
> > Your flutter app should interact like this
> 
> Like here yes? https://medium.com/@info_4766/build-a-marketplace-in-your-flutter-app-and-accept-payments-using-stripe-and-firebase-59f074201718

yes, but change few things according to your what you sell.

**Comment by fipooo** [comment]
> > > ![image](https://user-images.githubusercontent.com/18236718/77770508-c86c5100-705e-11ea-8b17-8e10e220f1ae.png)
> > > Your flutter app should interact like this
> > 
> > 
> > Like here yes? https://medium.com/@info_4766/build-a-marketplace-in-your-flutter-app-and-accept-payments-using-stripe-and-firebase-59f074201718
> 
> yes, but change few things according to your what you sell.

Ok so I want to try and understand this and I do it. But now I have problem on firebase, the function give me this:  Error clone:  { Error: In order to share a PaymentMethod, you must pass a connected account ID by using an OAuth key or the Stripe-Account header.

**Comment by mario202k** [comment]
```
import * as functions from 'firebase-functions';
import { assert, assertUID } from './helpers';
import { getOrCreateCustomer } from './customers';

export const stripeSecret = functions.config().stripe.secret;

import Stripe from 'stripe';

const stripe = new Stripe(stripeSecret, {
  apiVersion: '2020-03-02',typescript:true
}); // TODO Set as Firebase environment variable

export const paymentIntent = functions.https.onCall( async (data, context) => {
  const amount = assert(data, 'amount');
  const paymentMethodId = assert(data,'paymentMethodId');
  const uid = assertUID(context);

  const customer = await getOrCreateCustomer(uid);


  const paymentIntent = await stripe.paymentIntents.create({
    amount:amount,
    currency: 'eur',
    payment_method_types: ['card'],
    customer: customer.id,
    payment_method: paymentMethodId,
    confirm:true,
    confirmation_method: 'manual'
});

console.log(paymentIntent.status);

return paymentIntent;
  
});
```

You need to pass the paymentMethod Id to the paymentIntent. I use Typescript.

**Comment by jonasbark** [comment]
Feel free to read the great official documentation at stripe.com. This github is a bad place to ask for support regarding stripe :)
