### ISSUE TITLE
What's the best way to get started with this payment package?

### ISSUE THREAD

**Issue by legut2** [jonasbark/flutter_stripe_payment#138]
I was wondering if anyone could tell me the simplest "getting-started" example that someone can think of for this package. I'm going to probably try the example in the example folder but I am flying blind. I've never used stripe before so I don't think it will be self-explanatory for myself.

I don't need to see google pay, or apple pay specific methods. A CC payment method is sufficient.

All the best,
Daniel

**Comment by awhitford** [comment]
I found this [article](https://medium.com/flutter-community/build-a-marketplace-in-your-flutter-app-and-accept-payments-using-stripe-and-firebase-72f3f7228625) to be very helpful, although the code snippets leave a little to be desired.

**Comment by legut2** [comment]
> I found this [article](https://medium.com/flutter-community/build-a-marketplace-in-your-flutter-app-and-accept-payments-using-stripe-and-firebase-72f3f7228625) to be very helpful, although the code snippets leave a little to be desired.

Thanks!
