### ISSUE TITLE
confirmCardPayment support

### ISSUE THREAD

**Issue by paperview** [jonasbark/flutter_stripe_payment#141]
seems confirmPaymentIntent is deprecated https://stripe.com/docs/js/deprecated/confirm_payment_intent

Any thoughts on possibly adopting the new confirmCardPayment?
https://stripe.com/docs/js/payment_intents/confirm_card_payment

thanks

**Comment by jonasbark** [comment]
Are these methods also deprecated on the Android / iOS sdk?

**Comment by paperview** [comment]
whoops, looks like they are not yet.  thanks!
