### ISSUE TITLE
Web Support for 0.1.0 package

### ISSUE THREAD

**Issue by peterjeffrey** [jonasbark/flutter_stripe_payment#146]
The 0.1.0 package indicates that there is Web support. However, my code is seemingly not working for this. 

I've configured Stripe credentials in the initState:
```
initState() {
    super.initState();

    StripePayment.setSettings(StripeSettings(
        publishableKey: "pk_test_**REAL CREDENTIAL HERE**",
        merchantIdentifier: "Test",
        androidProductionEnvironment: false));
  }
```

I call the following function when the user clicks "Add Card" and hope for a popup to appear for the user to present credentials. Unfortunately, nothing is happening and no error message prints.

```
StripePayment.addSource().then((token) {
                      Firestore.instance.collection('cards').document(widget.userID).collection('tokens').add({'tokenID': token}).then((val) {
                        print('saved');
                      });
                    }).catchError((e) {
                      print(e);
                    });
```

Is there web support for this?

**Comment by jonasbark** [comment]
Sorry, no. None planned as well but I'm happy to accept contributions in this area.
