### ISSUE TITLE
How could I set language as English

### ISSUE THREAD

**Issue by XinwenCheng** [jonasbark/flutter_stripe_payment#152]
Version is ```stripe_payment: ^1.0.7```, and please refer to following screenshot, my question is how i could set UI language of card form to English even my system language is Chinese? I've already set ```supportedLocales: [const Locale('en','US')]``` to ```MaterialApp```.

Thanks in advance!

```dart
@override
Widget build(BuildContext context) {
  return MaterialApp(
    title: '***',
    theme: themeData,
    darkTheme: themeData,
    routes: RouteConstant.getInstance().routes,
    home: SplashPage(),
    supportedLocales: [const Locale('en','US')],
  );
}
```
![screenshot_card_form](https://user-images.githubusercontent.com/795334/81885056-1831b800-95cc-11ea-8e4f-17e38156d125.png)

**Comment by jonasbark** [comment]
It relies on UI provided by Stripe themselves instead of the Flutter one. 
More information: https://github.com/jonasbark/flutter_stripe_payment/issues/7
