### ISSUE TITLE
What are the steps to go to production ?

### ISSUE THREAD

**Issue by EArminjon** [jonasbark/flutter_stripe_payment#160]
Hi,

I'm a quick lose when jumping between the doc from react native / stripe api / android api / apple api & developer console.

What is the step to go to production with this stripe package ? 

Must I https://developers.google.com/pay/api/android/guides/test-and-deploy/request-prod-access ?

**Comment by EArminjon** [comment]
Or just this lines is enough ?
```dart
 StripePayment.setOptions(StripeOptions(
      publishableKey: stripe_key,
      merchantId: merchantIdForApple,
      androidPayMode: 'production'
);
```

**Comment by Kretin1** [comment]
You only need to follow those instructions if you want to include Google Pay, but you must follow them to use Google Pay

**Comment by joelsonrocha** [comment]
> Ou apenas essas linhas são suficientes?
> 
> ```dart
>  StripePayment . setOptions ( StripeOptions (
>       publishableKey : stripe_key,
>       merchantId : merchantIdForApple,
>       androidPayMode :  'produção' 
> );
> ```
> 
> ```java
> < meta - dados
>                 android : name = " com.google.android.gms.wallet.api.enabled " 
>                 android : value = " true "  / >
> ```

Were you able to put it into production?
I Have an ERROR: Request Failed - Unexpected developer error, please try again later.
My question is: in merchantId (Google Pay MerchantId or Stripe MerchantId).
And where I inform Google Pay, the integration with Stripe, Google Pay has already authorized my application for production.
The documentation is not clear about the steps to put into production.
