### ISSUE TITLE
Cannot create source with credit card

### ISSUE THREAD

**Issue by vincenttarrit** [jonasbark/flutter_stripe_payment#161]
Hello everyone,
I try to pay with WooCommerce API and it needs a source id to process the payment. But when I try to create a source I get this exception :

PlatformException (PlatformException(api, The payment method `card` requires the parameter: card[number]., null)) 

this is my code : 
 Source source = await StripePayment.createSourceWithParams(
        SourceParams(type: "card", card: card)); 

where card is the CreditCard object with card number, expiry month, expiry year, cvc

I don't understand why the card number is null... This is the same case with the CardFormRequest and a credit card write in Object with CreditCard card = CreditCard(......);

Can you explain me the problem and how to fix it ? 

Thank you !
Vincent

**Comment by naoaki-kaito** [comment]
@vincenttarrit 
Hello, I saw same problem right now.
How did you solve?
