### ISSUE TITLE
Get saved paymentMethods from Customer

### ISSUE THREAD

**Issue by emmaxCreative** [jonasbark/flutter_stripe_payment#166]
Is it possible to get saved creditcards from a stripe customer?

**Comment by emmaxCreative** [comment]
nevermind I used a second package to get the customer and save creditcardinfos to the customer.

**Comment by knoja4** [comment]
> nevermind I used a second package to get the customer and save creditcardinfos to the customer.

Hi, would you mind telling what the 2nd package is that u used to handle retrieving and saving customer payment methods?

**Comment by emme1009** [comment]
@knoja4 Sure. I used ezet/stripe_sdk. Works great in combination with this one.

**Comment by knoja4** [comment]
Thanks a lot @emme1009 🤙🏾
