### ISSUE TITLE
Unresolved References

### ISSUE THREAD

**Issue by JPyke3** [jonasbark/flutter_stripe_payment#17]
Hi all!

Firstly thanks for the great work on the plugin! Its really awesome!

Was just wondering if I am having an issue with just my instance (Aka I have done something horribly wrong). Or if this is a known issue. I am also a complete android noob and this is only really my first time ever using it (Sorry about that).

When trying to build the app for android I get a whole bunch of unresolved references. As can be seen [here](https://pastebin.com/MySTeqRm).

Furthermore, when i open `stripe-payment/java/de.johnasbark.stripepayment/StripeDialog` I can see a whole bunch of Unresolved References. As can be seen [here](https://imgur.com/a/Qe9ibJQ).

Also, as per the footnote in the readme, i have extended my main activity to look as such: 
`public class MainActivity extends FlutterFragmentActivity {`

Any feedback would be appreciated! Thanks for taking the time! You guys are awesome 👍🏼

**Comment by JPyke3** [comment]
Ah, that merge would do it! 😂

**Comment by jonasbark** [comment]
Yes - please try version 0.1.0 (should be available in a few minutes) and report back if that fixed your issue.

**Comment by JPyke3** [comment]
Shall do! Hows that for customer service!? 👍🏼

**Comment by JPyke3** [comment]
Works like a dream! Thanks alot for the help!
