### ISSUE TITLE
Execution failed for task ':stripe_payment:compileDebugKotlin'.

### ISSUE THREAD

**Issue by jeanpier05** [jonasbark/flutter_stripe_payment#170]
e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_payment-0.1.1\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (43, 15): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Dialog?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_payment:compileDebugKotlin'.
> Compilation error. See log for more details

Help me!

**Comment by jonasbark** [comment]
Please use the latest version of this Plugin.
