### ISSUE TITLE
Apple Pay - Processing Payment - Not Completed

### ISSUE THREAD

**Issue by robert-stevens** [jonasbark/flutter_stripe_payment#177]
Hi Guys,

I wanted to know how to get Apple Pay to work, I have followed this guide and created a merchant ID and added it to XCode:

https://stripe.com/docs/apple-pay

And had a look at the example app.

When the user hits the checkout screen I create a Payment Intent via our API  which returns back a PaymentIntent response. And store the response in the state.

```{
    "id": "PAYMENT_INTENT_ID",
    "object": "payment_intent",
    "amount": 100,
    "amount_capturable": 0,
    "amount_received": 0,
    "application": null,
    "application_fee_amount": null,
    "canceled_at": null,
    "cancellation_reason": null,
    "capture_method": "automatic",
    "charges": {
        "object": "list",
        "data": [],
        "has_more": false,
        "total_count": 0,
        "url": "/v1/charges?payment_intent=PAYMENT_INTENT_ID"
    },
    "client_secret": "SOME_SECRET",
    "confirmation_method": "automatic",
    "created": 1593777290,
    "currency": "gbp",
    "customer": null,
    "description": null,
    "invoice": null,
    "last_payment_error": null,
    "livemode": false,
    "metadata": [],
    "next_action": null,
    "on_behalf_of": null,
    "payment_method": null,
    "payment_method_options": {
        "card": {
            "installments": null,
            "network": null,
            "request_three_d_secure": "automatic"
        }
    },
    "payment_method_types": [
        "card"
    ],
    "receipt_email": null,
    "review": null,
    "setup_future_usage": null,
    "shipping": null,
    "source": null,
    "statement_descriptor": null,
    "statement_descriptor_suffix": null,
    "status": "requires_payment_method",
    "transfer_data": null,
    "transfer_group": null
}```


I then launch apple pay via:


```
                          StripePayment.paymentRequestWithNativePay(
                            androidPayOptions: AndroidPayPaymentRequest(
                              totalPrice: '${widget.membershipOption.price}',
                              currencyCode: "GBP",
                            ),
                            applePayOptions: ApplePayPaymentOptions(
                              countryCode: 'GB',
                              currencyCode: 'GBP',
                              items: [
                                ApplePayItem(
                                  label: widget.membershipOption.title,
                                  amount: 100,
                                )
                              ],
                            ),
                          ).then((token) {
                            setState(() {
                              _scaffoldKey.currentState.showSnackBar(SnackBar(
                                  content: Text('Received ${token.tokenId}')));
                              _paymentToken = token;
                            });
                          }).catchError(setError);```

Processing responses:

![Screenshot 2020-07-03 at 14 18 07](https://user-images.githubusercontent.com/32265535/86468658-2b454680-bd38-11ea-8644-cf4c20075c80.png)

![Screenshot 2020-07-03 at 14 18 17](https://user-images.githubusercontent.com/32265535/86468663-2f716400-bd38-11ea-8a71-99747bf16617.png)

I have tried on a real device using real cards and the same happens.

What am I missing?

**Comment by RahulDevCodiant** [comment]
I am also facing the similar issue!!!

Please help!!!

**Comment by macmatrix** [comment]
Check out this [guide](https://medium.com/flutter-community/build-a-marketplace-in-your-flutter-app-and-accept-payments-using-stripe-and-firebase-72f3f7228625). 
It's working for me

**Comment by robert-stevens** [comment]
@macmatrix tx, had a quick look and doesn't seem that the guide is using Apple Pay?

I will give it a go though, perhaps it will help.

**Comment by DevRahul123** [comment]
Hi @robert-stevens 

My issue got resolved when i've used "await StripePayment.completeNativePayRequest();" in the first line of ".then(token)" method, like this :

.then((token) async {
  await StripePayment.completeNativePayRequest();
  //do anything with token
})

I found this solution here : https://github.com/tipsi/tipsi-stripe/issues/562

**Comment by robert-stevens** [comment]
@DevRahul123 thank you, I will give that a try.

**Comment by macmatrix** [comment]
> @macmatrix tx, had a quick look and doesn't seem that the guide is using Apple Pay?
> 
> I will give it a go though, perhaps it will help.

It does use Apple pay, G pay & standard credit card form! Have a look at it

**Comment by robert-stevens** [comment]
@macmatrix thanks will take time to go through it in detail.

**Comment by robert-stevens** [comment]
> Hi @robert-stevens
> 
> My issue got resolved when i've used "await StripePayment.completeNativePayRequest();" in the first line of ".then(token)" method, like this :
> 
> .then((token) async {
> await StripePayment.completeNativePayRequest();
> //do anything with token
> })
> 
> I found this solution here : [tipsi/tipsi-stripe#562](https://github.com/tipsi/tipsi-stripe/issues/562)

This worked for me. Thank you @DevRahul123

**Comment by haifzhan** [comment]
I had the same issue and have it solved. Please see my post here https://stackoverflow.com/questions/66899675/flutter-stripe-payment-native-pay-not-chargedapple-pay-and-google-pay/66945461#66945461
