### ISSUE TITLE
cant get stripe package from pub

### ISSUE THREAD

**Issue by hipimy** [jonasbark/flutter_stripe_payment#18]
error on get packages:
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

depends on stripe_payment >=0.0.9 which requires SDK version >=2.1.0 <3.0.0, version solving failed.

pub get failed (1)

my pubspec.yaml
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

**Comment by jonasbark** [comment]
Then you should update your Flutter version or the environment definition in your pubspec. Are you forced to use an older version?

**Comment by hipimy** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.407], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] IntelliJ IDEA Community Edition (version 2018.2)

environment:
  sdk: ">=2.1.2-dev.0.0 <3.0.0"

already upgrade flutter and can get pub pakages, then error come when to build.
e: C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (63, 36): Unresolved reference: let
e: C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (63, 42): Cannot infer a type for this parameter. Please specify it explicitly.
e: C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (85, 31): Unresolved reference: let
e: C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (86, 43): Unresolved reference: it
e: C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (94, 19): Unresolved reference: let
e: C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (95, 31): Unresolved reference: it
e: C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\kotlin\de\jonasbark\stripepayment\StripePaymentPlugin.kt: (14, 10): Unresolved reference: JvmStatic
e: C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\kotlin\de\jonasbark\stripepayment\StripePaymentPlugin.kt: (26, 33): Unresolved reference: let
e: C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\kotlin\de\jonasbark\stripepayment\StripePaymentPlugin.kt: (26, 38): Cannot infer a type for this parameter. Please specify it explicitly.
e: C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\kotlin\de\jonasbark\stripepayment\StripePaymentPlugin.kt: (27, 65): Unresolved reference: apply
e: C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\kotlin\de\jonasbark\stripepayment\StripePaymentPlugin.kt: (29, 25): Unresolved reference: show
e: C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\kotlin\de\jonasbark\stripepayment\StripePaymentPlugin.kt: (31, 25): Unresolved reference: tokenListener
e: C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\kotlin\de\jonasbark\stripepayment\StripePaymentPlugin.kt: (31, 43): Cannot infer a type for this parameter. Please specify it explicitly.
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by JPyke3** [comment]
Not sure if this at all helps. But I couldn't run this plugin on `Stable` I could only run this on `Master`. Perhaps run `flutter channel master` then `flutter upgrade`. Then see how it goes.

**Comment by JPyke3** [comment]
Oh and in your `Pubspec.yaml` file, change the `sdk` value to: `sdk: ">=2.1.0 <3.0.0"`

**Comment by hipimy** [comment]
@JPyke3 . change change to `sdk value to: sdk: ">=2.1.0 <3.0.0"`.
if change then break.
`The current Dart SDK version is 2.1.2-dev.0.0.flutter-0a7dcf17eb.
 requires SDK version >=2.1.2 <3.0.0, version solving failed.
pub get failed (1). `
Pub packages get currently no issues, maybe now the issues was moving when try to run build .

**Comment by JPyke3** [comment]
@hipimy did you change your Flutter Channel? your `Flutter Doctor` shows you are running `Flutter (Channel stable, v1.2.1`. If you change to `Master` this should resolve your issue.

**Comment by jonasbark** [comment]
The constraint that the plugin uses is `sdk: ">=2.1.0 <3.0.0"` so I really wonder what the issue should be here.

**Comment by JPyke3** [comment]
Sorry @hipimy I misread your response.

My mistake, it looks like now your error could be related to the android footnote on the `README`:
```
Please be aware that your main activity must extend from FlutterFragmentActivity. Otherwise the Android dialog would've looked very nasty.
```

Essentially the solution is, navigate to `android/app/src/main/java/com/(YourTeam)/(YourApp)` and open `MainActivity.java`

Then change the line below the imports to:
```
public class MainActivity extends FlutterFragmentActivity {
```

**Comment by hipimy** [comment]
Already change to master channel, still got same error when build. I already edit main activity to:
`public class MainActivity extends FlutterFragmentActivity {`.
 I think need open new ticket regarding build issues,because current pub packages, problem resolved . The problem moving when run and build. it seems related to kotlin. Should i apply kotlin plugin in build gradle.

**Comment by JPyke3** [comment]
Worth a shot. In my personal project's `build.gradle` I have `apply plugin: 'kotlin-android-extensions'`.

Getting no issues on android build. Let us know how you go.

**Comment by jonasbark** [comment]
Yes, please try adding this line to your buildscript dependency:

`classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"` (e.g. 1.3.21)

The kotlin-android-extensions plugin won't be necessary afaik.

**Comment by jonasbark** [comment]
Does it work for you?

**Comment by hipimy** [comment]
@jonasbark still not working even add kotlin.

**Comment by jonasbark** [comment]
Can you provide a sample app for me to look at?

**Comment by hipimy** [comment]
Finally resolve ,now can run and build.
Modified the build gradle in your packages to use kotlin jdk 8. i think because my project use java jdk 10.
C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android
```
dependencies {
    api 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.21'
    api 'com.stripe:stripe-android:6.1.2'
}
```

Even now my project did not include kotlin dependency still can run.so i think just change your package gradle resolve the error and i still use flutter on stable channel.

**Comment by jonasbark** [comment]
Thanks for letting us know. Closing this issue.
