### ISSUE TITLE
.createTokenWithCard() crashes the app immediately

### ISSUE THREAD

**Issue by herrmartell** [jonasbark/flutter_stripe_payment#184]
Right now it seems the app is crashing as soon as I try to create a payment token.

```dart
card = CreditCard(
        number: number,
        expMonth: int.parse(expMonth),
        expYear: int.parse(expYear),
        name: name,
        cvc: cvv,
      );

      Token token = await StripePayment.createTokenWithCard(card);
```

I'm not getting any error message whatsoever, not even running the app in debug mode seems to help. I just see the token as null, and then the app crashes.

Is this because I'm making a mistake or because this plugin is using a version of the Stripe SDK way too old? Is this plugin still being supported? 

Thanks!

**Comment by dsourav** [comment]
i am also facing the same issue...it worked me a couple of days ago...

**Comment by ollydixon** [comment]
You need to add the publishable key.

```
StripePayment.setOptions(StripeOptions(
      publishableKey: config.stripKey,
    ));
StripePayment.setStripeAccount('account_key_found_in_settings');
```

**Comment by jonasbark** [comment]
If the comment from @ollydixon didn't help you please provide a minimal reproducible example or at least some stacktraces.
