### ISSUE TITLE
[Android] HttpException 

### ISSUE THREAD

**Issue by cedricvp** [jonasbark/flutter_stripe_payment#19]
Hi 

I have a problem just when I add flutter_stripe_payement on pubspec.yaml on Android. If I remove the package, everything works.  The version use is 0.1.0

> Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:54226/ws

I have no idea to resolve this bug, can you help me ? Apparently it's a problem with the proxy but I don't know where is exactly the bug and how to fix it.

I don't have Android device, I use simulator for my test.
On iOs everything work correctly. 

flutter doctor -v

> [✓] Flutter (Channel dev, v1.3.9, on Mac OS X 10.14.3 18D109, locale fr-BE)
    • Flutter version 1.3.9 at /Users/user/Documents/flutter-sdk
    • Framework revision f91df4abe1 (3 days ago), 2019-03-09 21:19:28 -0500
    • Engine revision 4e54bc93ca
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 2fb6cd9f5f)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3
[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
[✓] VS Code (version 1.32.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0
[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
• No issues found!

flutter -v --bug-report run
> [   +9 ms] Installing build/app/outputs/apk/app.apk...
[        ] executing: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r /Users/user/Documents/app/flutter/app/build/app/outputs/apk/app.apk
[+2848 ms] Success
[        ] Installing build/app/outputs/apk/app.apk... (completed in 2,8s)
[   +4 ms] executing: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo -n 5722f961e14385d9255634f7674007ce01ea460a > /data/local/tmp/sky.com.company.app.sha1
[  +21 ms] Android SDK built for x86 startApp
[   +1 ms] executing: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.company.app/com.company.app.MainActivity
[ +118 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.company.app/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+1432 ms] Observatory URL on device: http://127.0.0.1:44475/
[   +1 ms] executing: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:44475
[  +10 ms] 54226
[        ] Forwarded host port 54226 to device port 44475 for Observatory
[   +5 ms] Connecting to service protocol: http://127.0.0.1:54226/
[  +37 ms] Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri =http://127.0.0.1:54226/ws
[   +2 ms] "flutter run" took 23 990ms.
[        ] "flutter run" took 23 990ms.
#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:413:7)<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:549:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async/runtime/lib/async_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async/runtime/lib/async_patch.dart:294:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete (dart:async/runtime/lib/async_patch.dart:28:18)
#23     _completeOnAsyncReturn (dart:async/runtime/lib/async_patch.dart:294:13)
#24     AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart)
#25     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:77:64)
#26     _rootRunUnary (dart:async/zone.dart:1132:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#31     Future._complete (dart:async/future_impl.dart:473:7)
#32     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#33     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:33:20)
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#39     _runPendingImmediateCallback (dart:isolate/runtime/lib/isolate_patch.dart:115:13)
#40     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:172:5)

If you need more data, ask me.

**Comment by jonasbark** [comment]
Does your app crash immediately? Can you check the Logcat for your Android device?

Did you notice this part in the readme:
`Please be aware that your main activity must extend from FlutterFragmentActivity. Otherwise the Android dialog would've looked very nasty.`?

**Comment by cedricvp** [comment]
My apologies, I forgot to change FlutterActivity to FlutterFragmentActivity. I didn't see this part in the readme, my bad.
With FlutterActivity my app crash immediately.

I change the extend and everything works find :)

Thanks for your reactivity and for your package.
