### ISSUE TITLE
Example App - iOS Build failing 

### ISSUE THREAD

**Issue by dw2kim** [jonasbark/flutter_stripe_payment#193]
For iOS, when I run the example from the scratch, I get the following error:

[!] CocoaPods could not find compatible versions for pod "stripe_payment":
In Podfile:
stripe_payment (from .symlinks/plugins/stripe_payment/ios)

^ This is obvious that the deployment target version should be 11 or higher:
https://github.com/jonasbark/flutter_stripe_payment/blob/master/ios/stripe_payment.podspec#L20

The example iOS app should have the deployment target version as 11 or higher as a default.

**Comment by jonasbark** [comment]
works fine for me on macOS 10.15.6 and Xcode 11 or Xcode 12

**Comment by dw2kim** [comment]
Fixed in #207
