### ISSUE TITLE
how to change the default card?

### ISSUE THREAD

**Issue by michealchow2324** [jonasbark/flutter_stripe_payment#20]
is it possible to change the default card on stripe?

**Comment by jonasbark** [comment]
what do you mean with "default card"?

**Comment by michealchow2324** [comment]
I mean the default credit card for stripe users if they added more than one card.

<img width="821" alt="螢幕快照 2019-03-25 下午6 26 08" src="https://user-images.githubusercontent.com/47425480/54912497-b3308400-4f2b-11e9-85c2-8e926ad0e0da.png">

**Comment by jonasbark** [comment]
That has got nothing to do with this library. The library is only meant as a way to input credit cards - not for handling them in the API.
I'm closing this ticket.
