### ISSUE TITLE
ignoring file building for iOS-armv7 but attempting to link with file built for iOS-arm64

### ISSUE THREAD

**Issue by freddy-nawfal** [jonasbark/flutter_stripe_payment#205]
Hello, I'm having this problem with the plugin since I upgraded to Flutter 1.22 and Xcode 12: 

```
warning: ignoring file /Users/___/Library/Developer/Xcode/DerivedData/Runner-caufzxrscmyulqgkebskodjgtkvb/Build/Products/Debug-iphoneos/Stripe/Stripe.framework/Stripe, building for iOS-armv7 but attempting to link with file built for iOS-arm64
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_STPAPIClient", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_STPSetupIntentConfirmParams", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_STPAppInfo", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_STPPaymentIntentParams", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_STPPaymentMethodParams", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_STPTheme", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_STPPaymentMethodBillingDetails", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_STPPaymentMethodAddress", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_STPCardParams", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_STPAddCardViewController", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_STPAddress", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_STPStringFromCardBrand", referenced from:
      -[StripeModule cardBrandAsPresentableBrandString:] in TPSStripeManager.o
  "_OBJC_CLASS_$_STPPaymentHandler", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_STPBankAccountParams", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_STPPaymentConfiguration", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_Stripe", referenced from:
      objc-class-ref in TPSStripeManager.o
     (maybe you meant: _OBJC_CLASS_$_StripePaymentPlugin, _OBJC_CLASS_$_StripeModule )
  "_OBJC_CLASS_$_STPPaymentMethodCardParams", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_STPUserInformation", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_STPRedirectContext", referenced from:
      objc-class-ref in TPSStripeManager.o
  "_OBJC_CLASS_$_STPSourceParams", referenced from:
      objc-class-ref in TPSStripeManager.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

And here is my flutter doctor: 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.49.3)
``` 

It looks like a problem with the stripe sdk but I'm not sure.

I would appreciate any help.

**Comment by ernest0vm** [comment]
this issue is generated by new Stripe iOS SDK (20.0.0)
[https://github.com/stripe/stripe-ios/blob/master/CHANGELOG.md](https://github.com/stripe/stripe-ios/blob/master/CHANGELOG.md)

this drops support for armv7 arch's, for solve you can **delete your pods folder** and overwrite your Podfile.lock when

```
- Stripe (20.0.0)
- stripe_payment (1.0.0):
  - Flutter
  - Stripe (>= 19.0.1)
```

change by 
```
- Stripe (19.0.1)
- stripe_payment (1.0.0):
  - Flutter
  - Stripe (>= 19.0.1)
```

then install pods again or run your flutter app, its worked for me

**Comment by freddy-nawfal** [comment]
Thanks, I solved it by adding armv7 as an excluded architecture. I guess it works too that way.

**Comment by RohithKilaparthi** [comment]
ernest0vm ```flutter run``` succeeds this way but ```flutter build ios --release``` fails for me

@freddy-nawfal how to add armv7 as an excluded architecture ?

How to solve the issue?

**Comment by ernest0vm** [comment]
@RohithKilaparthi to exclude an architecture just add **armv7** into 
**Runner > Build Settings > Excluded Architectures**

if you cannot see this option use search box

![image](https://user-images.githubusercontent.com/11278416/96469274-a56bdf00-11f2-11eb-9429-d84240d8f1cb.png)

**Comment by RohithKilaparthi** [comment]
@ernest0vm I dont see excluded architecture in my build settings, rather, I see Valid Architecture, I removed both armv7 and armv7s, tried building and it failed. Later I checked build active architectures only and tried building, the result is same. I tried searching for excluded architectures, I don't see any result

<img width="602" alt="Screenshot 2020-10-20 at 9 22 41 AM" src="https://user-images.githubusercontent.com/13035828/96538347-f85a9a80-12b5-11eb-9dac-0bebe83e2158.png">

**Comment by freddy-nawfal** [comment]
@RohithKilaparthi  Make sure you have selected basic/combined, or search for it in the search bar 

<img width="696" alt="Capture d’écran 2020-10-20 à 12 21 26" src="https://user-images.githubusercontent.com/9128521/96573676-ca358480-12ce-11eb-89f4-3c2c6a0f9455.png">

**Comment by RohithKilaparthi** [comment]
Fixed now, thanks @freddy-nawfal 
Updated X-Code to the latest version and add armv7 in excluded architectures.

**Comment by mgalgs** [comment]
For future googlers: in the latest xcode you have to select "All" instead of "Basic" to see the Architectures section.
