### ISSUE TITLE
Running into lots of Unresolved References

### ISSUE THREAD

**Issue by yongping95** [jonasbark/flutter_stripe_payment#21]
Flutter Doctor: Everything is good
Attempt to integrate this package into my existing project which didn't include Kotlin support in the first place. (Using Android Studio)
I've changed the MainActivity from extending FlutterActivity to FlutterFragmentActivity and figure out that I needed kotlin. I added the following lines of code and manipulated for a long time but didn't help.

build.gradle
buildscript {
    ext.kotlin_version = '1.3.30'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlin_version"
    }
}

build.gradle(App)
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

Error:
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (4, 12): Unresolved reference: google
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (5, 17): Unresolved reference: fragment
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (17, 31): Unresolved reference: fragment
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (25, 18): Unresolved reference: arguments
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (31, 5): 'onCreateView' overrides nothing
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (36, 5): 'onViewCreated' overrides nothing
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (37, 15): Unresolved reference: onViewCreated
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (40, 21): Unresolved reference: arguments
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (41, 9): Unresolved reference: dialog
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (49, 5): 'onCreate' overrides nothing
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (51, 15): Unresolved reference: onCreate
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (53, 9): Unresolved reference: setStyle
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (53, 27): Unresolved reference: fragment
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (59, 32): Unresolved reference: view
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (65, 17): Unresolved reference: view
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (66, 17): Unresolved reference: view
.
.
.
e: C:\Users\...\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\kotlin\de\jonasbark\stripepayment\StripePaymentPlugin.kt: (29, 25): Unresolved reference: show

**Comment by PerfectedApp** [comment]
Also facing the same issue

**Comment by jonasbark** [comment]
can you provide a minimal example app showcasing the error?

**Comment by PerfectedApp** [comment]
@jonasbark I could give you access to my private repo that has the code if you like. It's not a large app. Would that do?

**Comment by PerfectedApp** [comment]
@jonasbark or it will take a few days before getting a sample.

**Comment by jonasbark** [comment]
Temporary access to your private repo is fine 👍 I think I can have a look by sunday.

**Comment by kalegd** [comment]
Any luck on figuring out what the issue is? I'm running into the same list of Unresolved References

**Comment by xai1983kbu** [comment]
@kalegd  check my answer https://stackoverflow.com/a/56174623/9783262
I hope it will be helpful temporary.

**Comment by kalegd** [comment]
Hi @xai1983kbu 
I use to use 0.0.9 but am currently upgrading to use AndroidX throughout my project. I was able to fix the issue by adding the following to android/gradle.properties in my project
```properties
android.useAndroidX=true
android.enableJetifier=true
```

@jonasbark Not sure if you'd like to add this to the README or not, but I've created a pull request that adds that information (#22)

**Comment by jonasbark** [comment]
Thanks for the contribution! 
@xai1983kbu @PerfectedApp can you confirm that this has fixed it for you as well?

**Comment by xai1983kbu** [comment]
@jonasbark  I confirm, this solution has fixed it for me as well (even for version ^0.1.0).

@kalegd may I add your solution to my answers?
[https://stackoverflow.com/questions/55492162/integrating-stripe-payment-in-flutter/56174623#56174623](https://stackoverflow.com/questions/55492162/integrating-stripe-payment-in-flutter/56174623#56174623)
[https://stackoverflow.com/questions/54850802/flutter-android-app-crashes-on-start-when-use-stripe-payment/56174806#56174806](https://stackoverflow.com/questions/54850802/flutter-android-app-crashes-on-start-when-use-stripe-payment/56174806#56174806)

**Comment by kalegd** [comment]
@xai1983kbu of course!
