### ISSUE TITLE
paymentRequestWithNativePay - PlatformException(stripe, 10: , null, null)

### ISSUE THREAD

**Issue by Navarad** [jonasbark/flutter_stripe_payment#219]
Hello,
recently I found some logs where I couldn't really tell what happened. The exception was triggered when calling paymentRequestWithNativePay method and the exception was: PlatformException(stripe, 10: , null, null). Do you have any ideas what is this about? Thanks

**Comment by DryDoge** [comment]
I have same issue ? any Idea ?

**Comment by Navarad** [comment]
caused by many decimal places, thanks very much
