### ISSUE TITLE
iOS Framework not found Stripe3DS2

### ISSUE THREAD

**Issue by scarranca** [jonasbark/flutter_stripe_payment#220]
Hi I'm building an app that suddenly stopped working on iOS.
(Android works fine)

stripe_payment: ^1.0.8

I'm getting this error: **framework not found Stripe3DS2** , if I delete the stripe_payment it runs normally.

I have tried to fixed changing Flutter channel to stable, main and beta.

Flutter Doctor
Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-MX)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.50.1)
[✓] Connected device (2 available)

Thanks in advance.

**Comment by OLayemii** [comment]
Having same issue, any solutions?

**Comment by OLayemii** [comment]
Check your cocoapods version with `pod env` the first line shows the version, if it's up to 1.10.0

`gem install cocoapods --pre`

update your cocoapods to 1.10.0

and retry.

and retry

**Comment by scarranca** [comment]
> gem install cocoapods --pre
