### ISSUE TITLE
'Stripe/Stripe.h' file not found error

### ISSUE THREAD

**Issue by graperaisin1** [jonasbark/flutter_stripe_payment#225]
Getting this error when running on iOS 14.2 (min version 11.0), using stripe_payment: ^1.0.8:

    /.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.8/ios/Classes/TPSStripeManager.h:11:9: fatal error: 'Stripe/Stripe.h' file not found
        #import <Stripe/Stripe.h>
                ^~~~~~~~~~~~~~~~~
        /.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.8/ios/Classes/TPSStripeManager.h:11:9: note: did not find header 'Stripe.h' in framework 'Stripe' (loaded from '/build/ios/Debug-iphonesimulator/Stripe')
        1 error generated.
        note: Using new build system
        note: Building targets in parallel
        note: Planning build
        note: Constructing build description
    Could not build the application for the simulator.
    Error launching application on iPhone 12 Pro Max.

Flutter doctor:

    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-AU) 
    [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    [✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    [✓] Chrome - develop for the web
    [✓] Android Studio (version 4.1)
    [✓] VS Code (version 1.51.1)
    [✓] Connected device (3 available)

Can anyone advise?

**Comment by danielo17** [comment]
I have exactly the same error here. I tried to play around with Podfile, but nothing seems to work. My application runs perfectly over Android, so I'm not looking too much in the code. I'm new to this library but seems to me from the installation instructions that no other action is needed. Tried to: pod install, flutter clear, flutter round, then upgrade pod version... Any help would be appreciated.

**Comment by TheArchitect123** [comment]
If you only need to generate the payment forms, then use this package instead:
https://pub.dev/packages/stripe_native

and manage the stripe transactions with a different library.

**Comment by eripe970** [comment]
I have exactly the same error here, no solution :/

**Comment by himanshukh** [comment]
Anyone get any solution for this error. I got same error in my running project. Please share if you find any solution for this.

**Comment by hasanzia1993** [comment]
Dealing with this error, is there another version which we can use for now?

**Comment by jonasbark** [comment]
Can someone provide an example project where this is happening?

**Comment by luishar0** [comment]
> Can someone provide an example project where this is happening?

I just did a quick test creating a new flutter project. 
Ran the boilerplate code which worked fine. 
Added the dependency: 
> stripe_payment: ^1.0.8

> Got the packages
> pod install

Tried running: Error shows up. 
I tried deployment target 12.0 and 13.0 with no luck.

[✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-MX)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.51.1)
[✓] Connected device (3 available)

**Comment by danielo17** [comment]
Same as @luishar0 here. 

Empty project gives the error as soon as I add the dependency in pubspec.yaml.

Maybe just to add (if it helps spotting the issue) that for Android works well.

**Comment by jonasbark** [comment]
I just created a new flutter project, set minimum deployment target to 10 and everything worked as expected using latest Flutter beta. So I'd really require an example project where it does not work.

I'll need additional information:
- check your cocoapods version. I'm using 1.10.0.
- check the generated Podfile.lock and tell me which Stripe version it uses. It should be Stripe (19.4.0).
- try running 1.0.9 from the master branch of this repository. This sets stripes dependency fixed to 19.4.0.

**Comment by luishar0** [comment]
> I just created a new flutter project, set minimum deployment target to 10 and everything worked as expected using latest Flutter beta. So I'd really require an example project where it does not work.
> 
> I'll need additional information:
> 
> * check your cocoapods version. I'm using 1.10.0.
> * check the generated Podfile.lock and tell me which Stripe version it uses. It should be Stripe (19.4.0).
> * try running 1.0.9 from the master branch of this repository. This sets stripes dependency fixed to 19.4.0.

Ok so I found some differences here: 

COCOAPODS: 1.10.0

PODS:
  - Flutter (1.0.0)
  - Stripe (21.0.1)
  - stripe_payment (1.0.0):
    - Flutter
    - Stripe (>= 19.0.1)

>  try running 1.0.9 from the master branch of this repository. This sets stripes dependency fixed to 19.4.0.

I'm not sure I know what to do with that point. Could you explain the steps needed to end up with the same versions as you?

**Comment by jonasbark** [comment]
You can set the URL to this github repository:
https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

**Comment by jvalentik** [comment]
I can confirm that setting manually `s.dependency 'Stripe', '~> 19.4.0'` and `s.ios.deployment_target = '10.0'` in stripe_payment.podspec fixes the issue.... Thanks @jonasbark

**Comment by luishar0** [comment]
> You can set the URL to this github repository:
> https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

That worked! 

I changed my yaml file to: 

>   stripe_payment: 
>     git:
>       url: git://github.com/jonasbark/flutter_stripe_payment.git

`pod install`
`pod update Stripe`

And the project runs now. 

Thank you @jonasbark :)

**Comment by jonasbark** [comment]
Alright, thanks for confirming. I updated it now on pub as well 👍
