### ISSUE TITLE
What's the future for this library?

### ISSUE THREAD

**Issue by wsakka** [jonasbark/flutter_stripe_payment#24]
Great library, I was using it until ran into issues on Flutter 1.5 upgrades (not exclusively because of this library). However, I can see that the last meaningful contribution was a few months ago so I'm wondering if the author(s) intend on continuing with this plugin and what type of roadmap (if any) that they have.

Thanks!

**Comment by jonasbark** [comment]
Hi! Have you been able to resolve the issues? What were they, regarding this package?

Currently there are no plans for additional features but I'm very willing to accept contributions. So the scope of this package remains entering the credit card data - for any additional API requests I recommend using https://pub.dev/packages/stripe_api. 

I'll still provide maintenance updates if needed.
