### ISSUE TITLE
What's the Stripe API versions of stripe_payment? Will it be updated with the new regulation?

### ISSUE THREAD

**Issue by sharoncabrera** [jonasbark/flutter_stripe_payment#25]
A new rule coming into effect on September 14, 2019 as part of PSD2 regulation in Europe, it will require changes to how European customers authenticate online payments. 
One necessary rule is to have updated the plugin with the new version of Checkout, the Payment Intents API.

Is this implementation integrated?

https://stripe.com/docs/strong-customer-authentication/plugins

**Comment by jonasbark** [comment]
I'm not sure what's needed here. This plugin doesn't actually offer payment or anything?

**Comment by sante85** [comment]
Is needed

**Comment by jeromebonjour** [comment]
Hi, 
Did you implement "Redirecting your customer to authorize a source" ?
https://stripe.com/docs/mobile/android/sources

**Comment by MRTLeo** [comment]
I think is referring to this problem.
<img width="624" alt="Schermata 2019-07-29 alle 15 40 39" src="https://user-images.githubusercontent.com/25492442/62053265-8b259a00-b217-11e9-8bde-8db279ffb809.png">
And the solution should be this but i have no idea how to implement it in flutter
[PaymentIntent API](https://stripe.com/docs/payments/payment-intents)

**Comment by kamami** [comment]
Same problem here. This plugin needs to be updated to work with the new regulation of SCA! I tried to find a workaround with the provided payment_intent API, but this plugin is the bottleneck and prevents a solution for the new regulation... Please update soon. If anyone has already another solution, please share.

**Comment by lroige** [comment]
Until this plugin updates, the best workarounds are to use a webView with stripe checkout or the [flutter billing](https://pub.dev/packages/flutter_billing) plugin with native google and apple pay.

**Comment by sante85** [comment]
When we do this update?

Il Lun 29 Lug 2019, 16:13 Laura Roigé <notifications@github.com> ha scritto:

**Comment by jonasbark** [comment]
I'm on vacation until mid of next week. Until then I'd happily accept pull
requests.

sante85 <notifications@github.com> schrieb am Mo., 29. Juli 2019, 16:16:

**Comment by jonasbark** [comment]
The plugin now uses the latest library versions of the Stripe dependencies. Is there anything more to do?

**Comment by jeromebonjour** [comment]
The best will be to implement the step 3 too :
https://stripe.com/docs/payments/payment-intents/android#new-payment-method
(Confirm the Payment with Stripe3ds2UiCustomization)
But maybe it's larger than scope of your plugin. It s not createSource only..

**Comment by kamami** [comment]
@jonasbark At the moment your plugin is using the charges API. Stripe is providing a guide in their documentation for migrating from charges to the new and needed Payment Intents. 
https://stripe.com/docs/payments/payment-intents/migration
So it would be really cool, if you could give us a working example how to achieve this new method "Payment Intents" and everything around it by using you wonderful plugin :)

Thanks and regards

**Comment by jonasbark** [comment]
Hi! 

I updated the plugin (version 0.2.0) to use the Payments Intent to create a payment method (instead of creating a Source). 
I'd love to add additional features as well - I'm trying to reach out to Stripe.

**Comment by matte5031** [comment]
Hello! Not sure where to start with theese changes. I used to just let the user add a card. Then later use that card to charge the customer when they make a payment. Can I not do that flow anymore with SCA? Do you guys go for the "AUTOMATIC CONFIRMATION" or "MANUAL CONFIRMATION" flow?

Confused on how to work with the new SCA flow, figured maybe someone who has implemented this would be kind to share how they integrated it with this plugin and how their checkout flow looks like? Thanks!

/Mattias

**Comment by kamami** [comment]
@jonasbark Could you maybe provide a documentation of how to do the new implementation with your plugin? A guide would be really appreciated :) Especially with the use of firebase functions!

**Comment by jonasbark** [comment]
I've only got experience with Stripe without the new SCA flow, so I can't help there. But the Stripe support is happy to help ;)
