### ISSUE TITLE
Google pay is not working in android device 

### ISSUE THREAD

**Issue by yashshah1610** [jonasbark/flutter_stripe_payment#250]
When I use the below code to make a payment using native pay method then I got following error

Method: -

StripePayment.setOptions(StripeOptions(
        publishableKey: StripeConfig.kPublishableKey,
        merchantId: "Test",
        androidPayMode: 'test'));
        
var token = await StripePayment.paymentRequestWithNativePay(
        androidPayOptions: AndroidPayPaymentRequest(
          totalPrice: amount,
          currencyCode: currency,
        ),
        applePayOptions: ApplePayPaymentOptions(
          countryCode: 'AU',
          currencyCode: currency,
          items: [
            ApplePayItem(
              label: 'Merrier Coffee',
              amount: amount,
            ),
          ],
        ),
      );
      
      
      
     Error : -

![Screenshot 2021-02-19 at 1 05 21 PM](https://user-images.githubusercontent.com/36261813/108472755-2a572a00-72b3-11eb-8cae-18e3f7244c8a.png)

**Comment by jonasbark** [comment]
The exception suggests that you publishable key is not set correctly

**Comment by yashshah1610** [comment]
yes thanks @jonasbark

**Comment by haifzhan** [comment]
I have pasted my solution on Google pay, the answer is here https://stackoverflow.com/questions/66899675/flutter-stripe-payment-native-pay-not-chargedapple-pay-and-google-pay/66945461#66945461
