### ISSUE TITLE
CocoaPods could not find compatible versions for pod "stripe_payment":

### ISSUE THREAD

**Issue by EMIkram** [jonasbark/flutter_stripe_payment#256]
When I run `pod install` on my flutter project this is the result:
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '6.33.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '6.33.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '6.33.0' defined in 'firebase_core'
**[!] CocoaPods could not find compatible versions for pod "stripe_payment":
  In Podfile:
    stripe_payment (from `.symlinks/plugins/stripe_payment/ios`)

Specs satisfying the `stripe_payment (from `.symlinks/plugins/stripe_payment/ios`)` dependency were found, but they required a higher minimum deployment target.**

[!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile.

The version I am using for stripe_payment in **pubspecs.yaml file is 1.0.10** which is latest version

**Comment by EMIkram** [comment]
i upgraded pod file and set # platform :ios, '10.0' but it didn't worked 
I resolved the issue by opening xcwokspace in x code in runner I upgraded my deployment target to 10.

**Comment by fabioselau077** [comment]
Hello, I'm having the same problem in Codemagic's iOS build.
How do I make this correction using VSCode? I don't have a mac.
