### ISSUE TITLE
is this can be use for checkout

### ISSUE THREAD

**Issue by jignesh2712** [jonasbark/flutter_stripe_payment#26]
sir is this reference code can be use for the checkout for an e-commerce app.

**Comment by jessetinell** [comment]
Yes. But it's not a complete "out of the box" solution.

You'll receive a token for the credit card. How you handle the token on **your server** is up to you.
You can create recurring payments (subscriptions) or one-time payments (e-commerce).

**Comment by jignesh2712** [comment]
Thank you for your response
