### ISSUE TITLE
CreditCard.fromJson() uses camel case instead of snake case

### ISSUE THREAD

**Issue by OMGloom** [jonasbark/flutter_stripe_payment#264]
Card object per stripe API: https://stripe.com/docs/api/cards/object uses snake case in field names.
CreditCard object tries to deserialize referencing fields in camel case
https://github.com/jonasbark/flutter_stripe_payment/blob/eaa2961d248e27fa94036591d3fa3904c4286244/lib/src/token.dart#L126-L146

This results in CreditCard object missing most of its fields when loaded from Stripe API.
Same applies to `toJson()` method

**Comment by jonasbark** [comment]
The API isn't used directly:
https://github.com/jonasbark/flutter_stripe_payment/blob/master/android/src/main/java/com/gettipsi/stripe/util/Converters.java#L95
