### ISSUE TITLE
Issues with Androidx

### ISSUE THREAD

**Issue by andyepx** [jonasbark/flutter_stripe_payment#27]
I have been trying to build for android with this library but running into a bunch of AndroidX related issues, seems like casting `registrar.activity() as androidx.fragment.app.FragmentActivity` does not work but I am not sure of what another solution could be?

Has anyone had a similar issue, is there any simple way to fix it? Happy to PR and investigate otherwise...

Thanks!

**Comment by jonasbark** [comment]
Did you read the https://github.com/jonasbark/flutter_stripe_payment#android part?

**Comment by andyepx** [comment]
Yeah - I am also using other libraries that use androidx like https://pub.dev/packages/firebase_auth and they work fine. The issue seems to be that the `MainActivity` class that Flutter creates in my app cant be casted to `androidx.fragment.app.FragmentActivity`: `java.lang.ClassCastException: my.app.MainActivity cannot be cast to androidx.fragment.app.FragmentActivity`...

Thanks!

**Comment by jonasbark** [comment]
Did you follow the instruction closely?
`Please be aware that your main activity must extend from *FlutterFragmentActivity*.`
As this is the reason I'm closing this issue.
