### ISSUE TITLE
international payment

### ISSUE THREAD

**Issue by SAKSHAM-flutter** [jonasbark/flutter_stripe_payment#275]
this kind of error show com.stripe.android.exception.InvalidRequestException: As per Indian regulations, export transactions require a customer name and address. More info here: https://stripe.com/docs/india-exports;
.
.
.
but i am not understand where is pass name and address.

my fuction is here:-
static Future payViaExistingCard(
{String amount, String currency, CreditCard card}) async {
try {
var paymentMethod = await StripePayment.createPaymentMethod(
PaymentMethodRequest(
card: card));
var paymentIntent =
await StripeService.createPaymentIntent(amount, currency);
var response = await StripePayment.confirmPaymentIntent(PaymentIntent(
clientSecret: paymentIntent['client_secret'],
paymentMethodId: paymentMethod.id));
if (response.status == 'succeeded') {
return new StripeTransactionResponse(
message: 'Transaction successful',
success: true,
id: paymentMethod.id.toString(),
);
} else {
return new StripeTransactionResponse(
message: 'Transaction failed',
success: false,
id: paymentMethod.id != null && paymentMethod.id != ""
? paymentMethod.id.toString()
: "12345",
);
}
} on PlatformException catch (err) {
return StripeService.getPlatformExceptionErrorResult(err);
} catch (err) {
return new StripeTransactionResponse(
message: 'Transaction failed: ${err.toString()}', success: false);
}
}

**Comment by kingfisher-tech** [comment]
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety: - package:stripe_payment

**Comment by SAKSHAM-flutter** [comment]
Here this work for me. I think billing address is necessary for dollar payment when u create stripe account in India.
