### ISSUE TITLE
Card number is not returned

### ISSUE THREAD

**Issue by TomMichalkevic** [jonasbark/flutter_stripe_payment#276]
When using a form provided by the library to gather card details from the user, the response provides the last4 digits and expiry date, however it does not provide the actual card number entered(gives null), which is required to initiate a payment

**Comment by jonasbark** [comment]
This is not true. If you use `paymentRequestWithCardForm` you'll receive the payment method from Stripe already with which you can initiate the payment.

**Comment by TomMichalkevic** [comment]
I'll give you a debug breakpoint output

**Comment by TomMichalkevic** [comment]
![image](https://user-images.githubusercontent.com/4348280/113394828-9a23fe80-93a1-11eb-951d-fb438ab5dfd6.png)

**Comment by TomMichalkevic** [comment]
I get the error later on that the card number is missing

**Comment by jonasbark** [comment]
It's on purpose that only the last 4 numbers are returned. You can check the Stripe API about that.

If you'll get an error later than you're using the wrong payment flow. You should not used the card object here but the payment method itself to make payments.

**Comment by TomMichalkevic** [comment]
Hmmm, will try it out

**Comment by TomMichalkevic** [comment]
![image](https://user-images.githubusercontent.com/4348280/113397989-934bba80-93a6-11eb-9698-3b745ccaaad3.png)
Something is not right though

**Comment by TomMichalkevic** [comment]
Sorry, I'm new to this. In terms of client secret, would that be the key from admin console or should it be generated?

**Comment by jonasbark** [comment]
Please read through https://medium.com/flutter-community/build-a-marketplace-in-your-flutter-app-and-accept-payments-using-stripe-and-firebase-72f3f7228625
It should answer your questions
