### ISSUE TITLE
Keyboard not popping up in ios Simulator to create PaymentIntent using a Credit card

### ISSUE THREAD

**Issue by Yunus0or1** [jonasbark/flutter_stripe_payment#280]
```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.6 19G2021 darwin-x64,
    locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)
```

Using stripe_payment: ^1.0.11

This is happening only in ios. Keyboard does not pop up to fill the Credit Card form. Even no error gets thrown.

![123](https://user-images.githubusercontent.com/11329052/115001284-55ca4f80-9ec5-11eb-9046-c45bc5d2a8a5.PNG)

**Comment by jonasbark** [comment]
I think you can turn on the soft keyboard in the Simulator setting - otherwise it just uses your PC keyboard.

**Comment by Yunus0or1** [comment]
Neither PC keyboard nor softkeyboard anything working. Just shows the paste button
