### ISSUE TITLE
Method not found: 'StripePayment.setOptions'

### ISSUE THREAD

**Issue by DevTiago** [jonasbark/flutter_stripe_payment#287]
I've followed the Docs, and on initState method i have error:

![image](https://user-images.githubusercontent.com/41440390/116435485-4fcc5b00-a843-11eb-8072-eda08b346aee.png)

![image](https://user-images.githubusercontent.com/41440390/116435512-58249600-a843-11eb-9379-48d008967d02.png)

Anyone facing the same issue?

**Comment by jonasbark** [comment]
please provide a minimal project where this issue can be reproduced

**Comment by DevTiago** [comment]
Hey @jonasbark, this issue can be closed. I've figured that i need to set the other options to get this done (merchantID and androidPayMode).

Thanks for your time.
