### ISSUE TITLE
Compile error on iOS

### ISSUE THREAD

**Issue by nachiketkhasbag** [jonasbark/flutter_stripe_payment#30]
_**I see a compile error when I try to run on iOS.**_

_**It builds fine when I run the demo app( i.e only stripe_payment package in my pubspec )
Fails when I have multiple packages in my pubspec.**_

_**Error:**_
`Launching lib/main.dart on iPhone Xs in debug mode...
Xcode build done.                                           16.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    In file included from /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.m:9:
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.h:30:68: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - (void)addCardViewControllerDidCancel:(STPAddSourceViewController *)addCardViewController;
                                                                       ^
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.h:30:68: note: insert '_Nullable' if the pointer may be null
    - (void)addCardViewControllerDidCancel:(STPAddSourceViewController *)addCardViewController;
                                                                       ^
                                                                        _Nullable
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.h:30:68: note: insert '_Nonnull' if the pointer should never be null
    - (void)addCardViewControllerDidCancel:(STPAddSourceViewController *)addCardViewController;
                                                                       ^
                                                                        _Nonnull
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.h:39:59: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - (void)addCardViewController:(STPAddSourceViewController *)addCardViewController
                                                              ^
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.h:39:59: note: insert '_Nullable' if the pointer may be null
    - (void)addCardViewController:(STPAddSourceViewController *)addCardViewController
                                                              ^
                                                               _Nullable
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.h:39:59: note: insert '_Nonnull' if the pointer should never be null
    - (void)addCardViewController:(STPAddSourceViewController *)addCardViewController
                                                              ^
                                                               _Nonnull
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.h:40:43: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
                   didCreateSource:(STPSource *)source
                                              ^
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.h:40:43: note: insert '_Nullable' if the pointer may be null
                   didCreateSource:(STPSource *)source
                                              ^
                                               _Nullable
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.h:40:43: note: insert '_Nonnull' if the pointer should never be null
                   didCreateSource:(STPSource *)source
                                              ^
                                               _Nonnull
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.h:41:32: warning: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
                       completion:(STPErrorBlock)completion;
                                   ^
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.h:41:32: note: insert '_Nullable' if the block pointer may be null
                       completion:(STPErrorBlock)completion;
                                   ^
                                                 _Nullable
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.h:41:32: note: insert '_Nonnull' if the block pointer should never be null
                       completion:(STPErrorBlock)completion;
                                   ^
                                                 _Nonnull
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.h:36:9: warning: parameter 'token' not found in the function declaration [-Wdocumentation]
     @param token                 the Stripe token that was created. @see STPToken
            ^~~~~
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.h:36:9: note: did you mean 'source'?
     @param token                 the Stripe token that was created. @see STPToken
            ^~~~~
            source
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.m:40:20: warning: incompatible pointer types initializing 'STPCardParams *' with an expression of type 'STPPaymentMethodCardParams *' [-Wincompatible-pointer-types]
        STPCardParams *cardParams = paymentCell.cardParams;
                       ^            ~~~~~~~~~~~~~~~~~~~~~~
    /Users/../flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-0.1.0/ios/Classes/STPAddSourceViewController.m:42:32: error: property 'managedAccountCurrency' not found on object of type 'STPAddSourceViewController *'
        cardParams.currency = self.managedAccountCurrency;
                                   ^
    6 warnings and 1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone Xs.
Exited (sigterm)
`

_**This is the output of flutter doctor:**_

`flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132,
    locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/../flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
    • Android SDK at /Users/../Library/Android/sdk
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • iPhone Xs • DCEF324A-8135-4355-81FA-B972772B42A4 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 1 category.`

_**I guess this issue is ok, I am not using Android studio at the moment.**_

pubspec:
`dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications:

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0
  firebase_core: ^0.4.0+8
  cloud_firestore: ^0.12.9
  google_sign_in: ^4.0.6
  firebase_messaging: ^5.1.2
  url_launcher: ^5.0.1
  flutter_auth_buttons: ^0.3.1
  geolocator: ^5.1.1
  stripe_payment: ^0.1.0
  cloud_functions: ^0.4.1`

**Comment by jonasbark** [comment]
Looks like you're using the wrong version of the stripe iOS dependency. How does the stripe specific part of your Podfile.lock file looks like?

**Comment by nachiketkhasbag** [comment]
Podfile.lock:

`- Stripe (16.0.3)
  - stripe_payment (0.0.1):
    - Flutter
    - Stripe`

`SPEC CHECKSUMS`:

`Stripe: 82a77b8dd26be83555f8ca9a3cc034dfda81fc40`
 `stripe_payment: bdd1575a69e8a74822e1febb3fd02192ff371c5a`

`SPEC REPOS:`
`- Stripe`

**Comment by nachiketkhasbag** [comment]
I was able to solve this with deintegrate pod.

`pod deintegrate`
`pod install`
