### ISSUE TITLE
[paymentRequestWithCardForm] Layout issue

### ISSUE THREAD

**Issue by tan-nad** [jonasbark/flutter_stripe_payment#305]
### **stripe_payment: v1.1.2**

The layout of card form is broken when tapping on any field in the second row. (using `paymentRequestWithCardForm`). 
It used to work in the previous version.

<img src="https://user-images.githubusercontent.com/70996203/122582510-714b0580-d082-11eb-83bf-5cbf8b73ad92.png" width="300">

It would be great if there is an option to hide the 'Postal code'.

**Comment by jonasbark** [comment]
I will hide it altogether

**Comment by tan-nad** [comment]
Are you sure it will work after hiding it?

**Comment by tan-nad** [comment]
Looks like the issue still happens. Could you please take a look again?

<img src="https://user-images.githubusercontent.com/70996203/122589825-ef130f00-d08a-11eb-965e-52fd4778abdd.png" width=300 />
