### ISSUE TITLE
How to change SDK version?

### ISSUE THREAD

**Issue by fabioselau077** [jonasbark/flutter_stripe_payment#307]
"Your app ---- version code --- includes SDK com.stripe:stripe-android, 10.4.6 which facilitates the transmission or collection of personal and sensitive information. Such behavior must comply with Google Play's Prominent Disclosure & Consent Requirements and applicable privacy policy requirements as described in the User Data policy.

Starting from July 11, 2021 midnight (UTC), new app releases containing this SDK version that do not meet the Prominent Disclosure & Consent Requirements per the User Data policy will be rejected. You may consider upgrading to 16.9.0, which the SDK provider has recommended for use instead. Please consult the SDK provider for further information."

**Comment by chwiz143** [comment]
According to this issue on the android stripe repo it should be enough to upgrade to the hotfixed `10.5.0` version.
https://github.com/stripe/stripe-android/issues/3864

**Comment by jonasbark** [comment]
It's already fixed in the latest release.

**Comment by Scienticious** [comment]
> 
> 
> It's already fixed in the latest release.

I have this same issue . Currently, I am using the Version 1.0.11 on Flutter 1.22.6, I can't use the latest version because it's using Dart 2.12 which uses flutter 2.

Any workaround to how to overcome this issue ?

Thanks

**Comment by EjazAmir** [comment]
> > It's already fixed in the latest release.
> 
> I have this same issue . Currently, I am using the Version 1.0.11 on Flutter 1.22.6, I can't use the latest version because it's using Dart 2.12 which uses flutter 2.
> 
> Any workaround to how to overcome this issue ?
> 
> Thanks

did you find any solution?

**Comment by soarHero** [comment]
> > It's already fixed in the latest release.
> 
> I have this same issue . Currently, I am using the Version 1.0.11 on Flutter 1.22.6, I can't use the latest version because it's using Dart 2.12 which uses flutter 2.
> 
> Any workaround to how to overcome this issue ?
> 
> Thanks

You can try

```
stripe_payment:
    git:
      url: https://github.com/soarHero/flutter_stripe_payment.git
      ref: 52fff88d8986cd6c6a8fe3ec70472fdd8c511bd9
```
I removed the "null safety" code and can be used for Flutter 1.22.
