### ISSUE TITLE
com.stripe.android.exception.InvalidRequestException: Keys for idempotent requests can only be used with the same parameters they were first used with.

### ISSUE THREAD

**Issue by SebghatYusuf** [jonasbark/flutter_stripe_payment#311]
I'm using a test publishable key and trying to make payment using the same card on both platforms (iOS, Android). 
When I run the app on iOS, everything is OK, and payment is done. 
but when I try to run the app on Android I see this error:
`com.stripe.android.exception.InvalidRequestException: Keys for idempotent requests can only be used with the same parameters they were first used with. Try using a key other than 'pk_test_********************************************************' if you meant to execute a different request.`

as I looked for the issue on the stripe documentation, they said the idempotency key is needed to be generated from client-side, so how I can generate this key? 

Traceback:

E/flutter (14813): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'FutureOr<bool>'
E/flutter (14813): #0      _FutureListener.handleError (dart:async/future_impl.dart:169:20)
E/flutter (14813): #1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:716:47)
E/flutter (14813): #2      Future._propagateToListeners (dart:async/future_impl.dart:737:24)
E/flutter (14813): #3      Future._completeError (dart:async/future_impl.dart:547:5)
E/flutter (14813): #4      _completeOnAsyncError (dart:async-patch/async_patch.dart:264:13)
E/flutter (14813): #5      StripePayment.createTokenWithCard (package:stripe_payment/src/stripe_payment.dart)
package:stripe_payment/src/stripe_payment.dart:1
E/flutter (14813): <asynchronous suspension>

**Comment by arasu33** [comment]
Same Issue for me.

**Comment by gopal-fp** [comment]
Same issue occurring..

**Comment by robertrobinson-augusta** [comment]
Same issue

**Comment by RohithKilaparthi** [comment]
Same issue

**Comment by jonasbark** [comment]
Anyone mind sharing some more information so I can reproduce this on the example app?

**Comment by SebghatYusuf** [comment]
@jonasbark 
For me I'm using CreditCard and then I'm passing it to the `createTokenWithCard` function. 

`StripePayment.createTokenWithCard(payCard)
          .then((token) {
            setState(() {
              _paymentToken = token;
            });
          })
          .then((value) => postToEndPoint())
          .catchError(
            (error) {
              print(error);
            },
          );` 
          It was working before on Android but from yesterday without any changes in my code I've faced this issue. 
          also it is currently working fine on iOS.

**Comment by robertrobinson-augusta** [comment]
All upgrade your gradle to latest

**Comment by SebghatYusuf** [comment]
@robertrobinson-augusta 
Thanks, just resolved my issue.

**Comment by SebghatYusuf** [comment]
@robertrobinson-augusta 
After the first build after I updated the gradle version it worked, but for the second build the issue occurred again. 
So I'm opening the issue again. and wait to get this issue resolved.

**Comment by SebghatYusuf** [comment]
@jonasbark Any updates? 
If you found out what is the problem please let us know, we are delaying the release only for this issue. 
Thank you.

**Comment by ivan-rangel** [comment]
Hi there, I was able to find a workaround for this.

I had to remove the `mPublicKey` param directly from the `StripeModule.java` and it worked.
![image](https://user-images.githubusercontent.com/2806537/123570903-c081ec00-d78e-11eb-81a4-8a64bc9a4d83.png)


I was checking the [stripe documentation](https://stripe.dev/stripe-android/stripe/com.stripe.android/create-card-token.html) and it seems the method accepts several params, however, I tested with all of them and only the Card data and the callback worked. Hope this helps someone

**Comment by SebghatYusuf** [comment]
@ivan-rangel Wow! Thank you, finally, a solution that worked well, but why is this happening, for example when I recompiled the app today, for the first time the payment was successful, but after the first payment I wasn't able to make another payment and got InvalidRequestException.

**Comment by ivan-rangel** [comment]
> @ivan-rangel Wow! Thank you, finally, a solution that worked well, but why is this happening, for example when I recompiled the app today, for the first time the payment was successful, but after the first payment I wasn't able to make another payment and got InvalidRequestException.

👋   I had the same issue the last week and I can assume that the idempotency key value is valid only for some time (this is why it works at the first time but later on tries do not) and for another weird reason, the stripe package for android is thinking that the public key provided as second params is the idempotency key, this is why just removing it from the code made the trick again and it starts working again.

**Comment by jonasbark** [comment]
idempotency key means it must only be used once, which is why it's working only once (and working again if you remove it altogether)

Feel free to create a PR with the fix :)

**Comment by jonasbark** [comment]
Fixed by 1.1.4

**Comment by palashsethiyab3** [comment]
stripe_payment 1.1.4

Thanks brother

**Comment by VianneySonneville** [comment]
mPublicKey has been remove from createTokenWithCard but not in createTokenWithBankAccount
`public void createTokenWithBankAccount(final ReadableMap accountData, final Promise promise) {
    try {
      ArgCheck.nonNull(mStripe);
      ArgCheck.notEmptyString(mPublicKey);

      mStripe.createBankAccountToken(
        createBankAccount(accountData),
        mPublicKey,
        null,
        new ApiResultCallback<Token>() {
          public void onSuccess(Token token) {
            promise.resolve(convertTokenToWritableMap(token));
          }
          public void onError(Exception error) {
            error.printStackTrace();
            promise.reject(toErrorCode(error), error.getMessage());
          }
        });
    } catch (Exception e) {
      promise.reject(toErrorCode(e), e.getMessage());
    }
  }`

is it possible to fix ?
