### ISSUE TITLE
Need support to use stripe_payment: ^1.0.4 

### ISSUE THREAD

**Issue by abhijeetvader9287** [jonasbark/flutter_stripe_payment#315]
Hi,
We have our project developed in 
 Flutter (Channel stable, v1.12.13+hotfix.5, on macOS 11.3.1 20E241, locale en-IN)
    • Flutter version 1.12.13+hotfix.5  
    • Framework revision 27321ebbad (1 year, 7 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

We have used stripe_payment: ^1.0.4 for payment. But right now it is not working anymore in iOs, It works fine in android.

Getting 
[!] CocoaPods could not find compatible versions for pod "Stripe":
  In Podfile:
    Stripe (from `https://github.com/stripe/stripe-ios.git`, tag `v19.4.0`)

Specs satisfying the `Stripe (from `https://github.com/stripe/stripe-ios.git`, tag `v19.4.0`)` dependency were found, but they required a higher minimum deployment target.
It would be great help if you help to resolve this.

**Comment by jonasbark** [comment]
> Specs satisfying the Stripe (from https://github.com/stripe/stripe-ios.git`, tag v19.4.0)` dependency were found, but they required a higher minimum deployment target.

It already tells you how to fix it. Check Google.

**Comment by abhijeetvader9287** [comment]
Thanks for the reply, But we are not in a position to upgrade the deployment target as whole project libraries need to be upgraded to the latest version also some of the libraries are already discontinued in the latest dart SDK. So we need to go with the older dart SDK. Can you please guide us on what we can do without upgrading the dart SDK?

**Comment by jonasbark** [comment]
You'll need to update the deployment target for iOS. It has nothing to do with the Dart SDK.
