### ISSUE TITLE
Transaction Failed: 'package:stripe_payment/src/stripe_payment.dart': Failed assertion: line 157 pos 12: 'intent.clientSecret !=null': is not true.

### ISSUE THREAD

**Issue by ketancts** [jonasbark/flutter_stripe_payment#316]
Transaction Failed: 'package:stripe_payment/src/stripe_payment.dart': Failed assertion: line 157 pos 12: 'intent.clientSecret !=null': is not true.
![Error](https://user-images.githubusercontent.com/78349298/124232366-2e336c80-db2f-11eb-8f09-1430dfdae154.PNG)

**Comment by deep1931** [comment]
Hello,
have you found the solution to this issue?

Regards

**Comment by ketancts** [comment]
@deep1931 Yes, Just re-verify your stripe_publishable_key and stripe_secret_key. Make sure both keys are for sandbox or for production. In my case one is for sandbox and second was for production.

**Comment by ketancts** [comment]
Yes @deep1931. Just verify your stripe_publishable_key and stripe_secret_key are correct.

Also, if you have added //'metadata': '', then comment it because empty map also produced 

static Future<Map<String, dynamic>> createPaymentIntent(
      String amount, String currency) async {
    try {
      Map<String, dynamic> body = {
        'amount': amount,
        'currency': currency,
        'payment_method_types[]': 'card',
        //'metadata': '',
      };
      var response = await http.post(Uri.parse(StripeService.paymentApiUrl),
          body: body, headers: StripeService.headers);
      return jsonDecode(response.body);
    } catch (err) {
      print('err charging user: ${err.toString()}');
    }
    return null;
  }
