### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by JosephhBh** [jonasbark/flutter_stripe_payment#326]
What happens when stripe introduce new updates ? such as security ....
Should i release an update for my application each time Stripe makes an update ?

Im asking this question in order to deside where should i put my payment part (backend or front end)

**Comment by jonasbark** [comment]
always prefer backend when possible
also don't use this plugin - use flutter_stripe ;)

**Comment by oliveyew** [comment]
@jonasbark check this easy way [here](https://www.udemy.com/course/flutter-in-app-consumable-non-consumable-purchase-2022/?couponCode=NEW_USER_DISCOUNT)
