### ISSUE TITLE
 Duplicate class com.nimbusds.jose.JWEObject found in modules jetified-threedssdk-release-1.1.17-runtime.jar

### ISSUE THREAD

**Issue by tarafat** [jonasbark/flutter_stripe_payment#334]
Duplicate class com.nimbusds.jose.Requirement found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-9.8.1.jar (com.nimbusds:nimbus-jose-jwt:9.8.1)
  Duplicate class com.nimbusds.jose.crypto.AESEncrypter found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-9.8.1.jar (com.nimbusds:nimbus-jose-jwt:9.8.1)
  Duplicate class com.nimbusds.jose.crypto.AESEncrypter$AlgFamily found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-9.8.1.jar (com.nimbusds:nimbus-jose-jwt:9.8.1)
  Duplicate class com.nimbusds.jose.crypto.impl.ECDH found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-9.8.1.jar (com.nimbusds:nimbus-jose-jwt:9.8.1)
  Duplicate class com.nimbusds.jose.crypto.impl.ECDH$AlgorithmMode found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-9.8.1.jar (com.nimbusds:nimbus-jose-jwt:9.8.1)
  Duplicate class com.nimbusds.jose.jwk.KeyOperation found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-9.8.1.jar (com.nimbusds:nimbus-jose-jwt:9.8.1)

  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>

**Comment by tarafat** [comment]
I was using both stripe and square dependencies on my project,commenting square dependencies solved the issue

**Comment by sahilkashyap64** [comment]
> I was using both stripe and square dependencies on my project,commenting square dependencies solved the issue

[Adding this solved my problem, cuz I wanted to use both](https://github.com/square/in-app-payments-react-native-plugin/issues/62#issuecomment-627163091)
