### ISSUE TITLE
please update stripe_android 10.3.1

### ISSUE THREAD

**Issue by sante85** [jonasbark/flutter_stripe_payment#34]
update deps

**Comment by sante85** [comment]
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.3.1
  ,2.3]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.nimbusds:nimbus-jose-jwt:7.7 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2
  .3.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends on project 'stripe_payment' which depends onto com.stripe:stripe-android@10.2.1
  -- Project 'app' depends onto net.minidev:json-smart@2.3
  -- Project 'app' depends onto com.nimbusds:nimbus-jose-jwt@7.7
  -- Project 'app' depends onto com.stripe:stripe-3ds2-android@1.1.6
  -- Project 'app' depends onto com.stripe:stripe-android@10.2.1

  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Comment by sante85** [comment]
in build.gradle

dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath 'com.google.gms:google-services:4.2.0'
    }

**Comment by jigarfumakiya** [comment]
@sante85 
 did you find any solution?

**Comment by sante85** [comment]
No. Error Is actual

Il mar 27 ago 2019, 12:47 Jigar Fumakiya <notifications@github.com> ha
scritto:

**Comment by sante85** [comment]
Do you want an example config?

Il mar 27 ago 2019, 12:48 Sante Stanisci <s.sante85@gmail.com> ha scritto:

**Comment by jeromebonjour** [comment]
Are you adding 3D secure to this plugin ?

**Comment by jonasbark** [comment]
Dependencies are updated - does that solve your problem?

**Comment by crushman1** [comment]
Nope, the problem still exists:
`Project 'app' depends on project 'stripe_payment' which depends onto com.stripe:stripe-android@10.3.1`

**Comment by jonasbark** [comment]
which other plugins have dependencies to the conflicting packages?

**Comment by jigarfumakiya** [comment]
can you update stripe plugin manually.

**Comment by crushman1** [comment]
> which other plugins have dependencies to the conflicting packages?

@jonasbark from what i can see, no other plugin uses the same dependencies. If anything, probably firebase.

**Comment by crushman1** [comment]
> can you update stripe plugin manually.

@jigarfumakiya How do i go about doing this?

**Comment by jigarfumakiya** [comment]
yes you can update stripe  plugin manually..

open project in android studio (just select android folder only)
after that now you can see Stripe gradle file.there you can update stripe dependencies.
any one you want.

**Comment by sante85** [comment]
Please you can writer and example?

Il mar 3 set 2019, 14:49 Jigar Fumakiya <notifications@github.com> ha
scritto:

**Comment by jigarfumakiya** [comment]
okay i will send you picture. ASAP

**Comment by jigarfumakiya** [comment]
hey, @sante85  sorry for the late response.

here open the android folder to android studio.
then it will look something like this. (if you opening the first time it will take some time)

![Screen Shot 2019-09-26 at 3 45 28 PM](https://user-images.githubusercontent.com/11865669/65680788-4bdbc400-e075-11e9-95a8-a4fa4986cdf4.jpg)

then find stipe_payment module .then open Gradle and set new Dependencies.
check this out.

![Screen Shot 2019-09-26 at 3 46 04 PM](https://user-images.githubusercontent.com/11865669/65680810-58601c80-e075-11e9-9c3a-11834077bb55.jpg)


Let me know if anything else.
