### ISSUE TITLE
While publing app on playstore got : Error  We've detected this app uses an unsupported version of Play billing. Please upgrade to Billing Library version 3 or newer to publish this app. 

### ISSUE THREAD

**Issue by developmentkws** [jonasbark/flutter_stripe_payment#340]
Please help me to solve this problem,

![Screenshot](https://user-images.githubusercontent.com/72291258/140868840-8f28c255-9722-4f82-962b-9955078f1efc.png)

**Comment by developmentkws** [comment]
Okay I just updated my project with latest flutter version (2.5.2) and it got solved.

**Comment by itsAyyazdev** [comment]
I faced the same issue, here is some workaround worked for me.
In your `android>app>build.gradle` add following line in dependencies.

` implementation ('com.android.billingclient:billing:4.0.0'){
        force = true
    }`

**Comment by oliveyew** [comment]
Check this easy way [here](https://www.udemy.com/course/flutter-in-app-consumable-non-consumable-purchase-2022/?couponCode=NEW_USER_DISCOUNT)
@itsAyyazdev @developmentkws
