### ISSUE TITLE
Apple M1 - Not Running on Simulator - Got Error 'symbols not found for architecture arm64'

### ISSUE THREAD

**Issue by ghulamsabir5353** [jonasbark/flutter_stripe_payment#342]
Xcode's output:
↳
    ld: warning: ignoring file /Users/ghulamsabir/"ProjectPath"/build/ios/Debug-iphonesimulator/Stripe/
    Stripe.framework/Stripe, missing required architecture arm64 in file
    /Users/ghulamsabir/"ProjectPath"/build/ios/Debug-iphonesimulator/Stripe/
    Stripe.framework/Stripe (2 slices)
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_STPAPIClient", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPSetupIntentConfirmParams", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPAppInfo", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPPaymentIntentParams", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPPaymentMethodParams", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPTheme", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPPaymentMethodBillingDetails", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPPaymentMethodAddress", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPCardParams", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPAddCardViewController", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPAddress", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_STPStringFromCardBrand", referenced from:
          -[StripeModule cardBrandAsPresentableBrandString:] in TPSStripeManager.o
      "_OBJC_CLASS_$_STPPaymentHandler", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPBankAccountParams", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPPaymentConfiguration", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_Stripe", referenced from:
          objc-class-ref in TPSStripeManager.o
         (maybe you meant: _OBJC_CLASS_$_StripePaymentPlugin, _OBJC_CLASS_$_StripeModule )
      "_OBJC_CLASS_$_STPPaymentMethodCardParams", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPUserInformation", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPRedirectContext", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPSourceParams", referenced from:
          objc-class-ref in TPSStripeManager.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at
    /System/Volumes/Data/SWE/macOS/BuildRoots/b8ff8433dc/Library/Caches/com.apple.xbs/Sources/rsyn
    c/rsync-55/rsync/rsync.c(244) [sender=2.6.9]
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

Could not build the application for the simulator.
Error launching application on iPhone 13.

**Comment by ghulamsabir5353** [comment]
Anyone can help me this issue?

**Comment by lifeapps-42** [comment]
try adding this in your Podfile
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64" # this
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES" # and this
    end
  end
end
```
Don't forget to flutter clean and reinstall pods
Worked for me

**Comment by ghulamsabir5353** [comment]
Hey @lifeapps-42
After deleting Podfile.lock and I'm trying to reinstall the pod install but getting error: 


Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

**Comment by lifeapps-42** [comment]
can you provide your Podfile here?

**Comment by ghulamsabir5353** [comment]
# Uncomment this line to define a global platform for your project
 platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64" # this
    end
  end
end

**Comment by ghulamsabir5353** [comment]
in /ios 
i run "arch -x86_64 pod install"

**Comment by ghulamsabir5353** [comment]
After running "arch -x86_64 pod install" 
I already struck on "Running pod install...  "

**Comment by lifeapps-42** [comment]
Please check my podfile code, you need to add one more line. 

I'm not really sure if it is the only reason, but try.

**Comment by ghulamsabir5353** [comment]
This PODFILE setting work for me 

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64" # this
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES" # and this
    end
  end
end
