### ISSUE TITLE
Not build - building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64 - Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by federico2390** [jonasbark/flutter_stripe_payment#346]
The plugin `stripe_payment` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Launching lib/main.dart on iPhone 13 in debug mode...
Xcode build done.                                            3,6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/zs/td00h4cd4qd9cmr4zpqv438m0000gn/T/flutter_tools.vgXEuo/flutter_ios_build_temp_dirguNBJJ/temporary_xcresult_bundle
    ld: warning: ignoring file /Users/federicodesalvatore/Desktop/ilviale1992/build/ios/Debug-iphonesimulator/Stripe/Stripe.framework/Stripe, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_STPAPIClient", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPSetupIntentConfirmParams", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPAppInfo", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPPaymentIntentParams", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPPaymentMethodParams", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPTheme", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPPaymentMethodBillingDetails", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPPaymentMethodAddress", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPCardParams", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPAddCardViewController", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPAddress", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_STPStringFromCardBrand", referenced from:
          -[StripeModule cardBrandAsPresentableBrandString:] in TPSStripeManager.o
      "_OBJC_CLASS_$_STPPaymentHandler", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPBankAccountParams", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPPaymentConfiguration", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_Stripe", referenced from:
          objc-class-ref in TPSStripeManager.o
         (maybe you meant: _OBJC_CLASS_$_StripePaymentPlugin, _OBJC_CLASS_$_StripeModule )
      "_OBJC_CLASS_$_STPPaymentMethodCardParams", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPUserInformation", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPRedirectContext", referenced from:
          objc-class-ref in TPSStripeManager.o
      "_OBJC_CLASS_$_STPSourceParams", referenced from:
          objc-class-ref in TPSStripeManager.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    Result bundle written to path:
    	/var/folders/zs/td00h4cd4qd9cmr4zpqv438m0000gn/T/flutter_tools.vgXEuo/flutter_ios_build_temp_dirguNBJJ/temporary_xcresult_bundle
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPAPIClient

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPSetupIntentConfirmParams

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPAppInfo
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPPaymentIntentParams

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPPaymentMethodParams

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPTheme

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPPaymentMethodBillingDetails
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPPaymentMethodAddress

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPCardParams

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPAddCardViewController

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPAddress
Error (Xcode): Undefined symbol: _STPStringFromCardBrand

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPPaymentHandler
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPBankAccountParams
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPPaymentConfiguration
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_Stripe
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPPaymentMethodCardParams
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPUserInformation
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPRedirectContext
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_STPSourceParams
Could not build the application for the simulator.
Error launching application on iPhone 13.
Exited (sigterm)

**Comment by sawankumarbundelkhandi** [comment]
Try this for workaround - https://github.com/flutter/flutter/issues/90382#issuecomment-929711305

**Comment by federico2390** [comment]
> Try this for workaround - https://github.com/flutter/flutter/issues/90382#issuecomment-929711305

I have opted for use flutter_stripe

**Comment by oliveyew** [comment]
Check this new way [here](https://www.udemy.com/course/flutter-in-app-consumable-non-consumable-purchase-2022/?couponCode=NEW_USER_DISCOUNT)
@federico2390
