### ISSUE TITLE
SCA and 2FA

### ISSUE THREAD

**Issue by matheusrezende** [jonasbark/flutter_stripe_payment#35]
Hi,

I'm using this plugin in our app and I saw the changes made to use the new SCA regulations.
I have some questions on how the 2FA authentication should be implemented after creating the payment intent.

I have worked for payment providers before and would like to be involved in the development if possible. How is the roadmap going to provide full support for 2FA?

**Comment by jonasbark** [comment]
Hi! 

I'm happy to merge pull requests regarding that feature. I'd like to work more on this plugin but I cannot find the time for it - as I have no personal / professional need anymore to update this plugin.

**Comment by jeromebonjour** [comment]
@matheusrezende I think we just have to add the Confirm the PaymentIntent step at this plugin
https://stripe.com/docs/payments/payment-intents/android#confirm-payment-intent

And this method :
ConfirmPaymentIntentParams
              .createWithPaymentMethodId(paymentMethodId, clientSecret,
                      returnUrl, false, extraParams);

Could you do it on IOS ? I will do it on Android.

**Comment by matheusrezende** [comment]
Sure I will do this part on IOS

**Comment by ayushin** [comment]
How is the progress? Do you need any help?

**Comment by kaessajidi** [comment]
I have done this on android. but I'm stuck on how to implement onActivityResult.
What I did is adding new method called set setClientSecret and
 now the usage should be as bellow: 

http.post("https://xxx.herokuapp.com/create_setup_intent").then((res) {
            var data = jsonDecode(res.body);
            StripeSource.setClientSecret(data['secret']);
            StripeSource.addSource().then((String token) {
              //Show card added successfully...
              ...
            });

          }); 


any help I'm not good on android LC classes ?

**Comment by mshafrir-stripe** [comment]
@kaessajidi I work on the Stripe Android SDK. Can you link directly to the code you've written (i.e. the exact class)? I may be able to help you.

**Comment by jonasbark** [comment]
I've seen a new plugin from @eopeter that does something like that:
https://github.com/eopeter/flutter_stripe_payment

@eopeter would you be willing to instead create a pull request to this plugin with your feature? Instead of creating a plugin with a very similar name?
I could do the Android implementation of your changes.

**Comment by eopeter** [comment]
@jonasbark the Android implementation is completed on my repo. I could do a pull-request but I think that will take a lot more work. We are actively developing for Stripe and intent to keep up with the latest Stripe versions for a while.

**Comment by jonasbark** [comment]
That will confuse the devs, but alright then.

**Comment by ezet** [comment]
I had the same issues and ended up using a slightly different approach. Feel free to test it out https://pub.dev/packages/stripe_sdk

**Comment by jonasbark** [comment]
Version 0.3.0 now supports:

* SCA and 2FA (two factor authentication)
* confirm + setup payments
* Apple / Google Pay via stripe_native (https://pub.dev/packages/stripe_native)

**Comment by sagar440** [comment]
How can i implement the 3D secure authentication using this plugin ? please help .

**Comment by deepakrana0011** [comment]
@sagar440 you get any solution for 3d secure payment with this plugin?
