### ISSUE TITLE
stripe payment with the error MissingPluginException (MissingPluginException(No implementation found for method setPublishableKey on channel stripe_payment))

### ISSUE THREAD

**Issue by jiawei016** [jonasbark/flutter_stripe_payment#38]
hi can help me on this ? i have face this issue for few days and no clues on this. others element is working fine, when implementing flutter_stripe then the error shows me 

    MissingPluginException (MissingPluginException(No implementation found for method 
    setPublishableKey on channel stripe_payment))

MainActivity file

    public class MainActivity extends FlutterFragmentActivity {
      override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(this)
      }
    }

build.gradle in android > app

    defaultConfig {
        (https://developer.android.com/studio/build/application-id.html).
        applicationId "app.app"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
     }

build.gradle in Android folder

    buildscript {
        ext.kotlin_version = '1.2.71'
        repositories {
            google()
            jcenter()
        }

        dependencies {
            classpath 'com.android.tools.build:gradle:3.4.2'
            classpath 'com.google.gms:google-services:4.2.0'
        }

        subprojects {
            project.configurations.all {
                resolutionStrategy.eachDependency { details ->
                    if (details.requested.group == 'androidx.core'
                            && !details.requested.name.contains('androidx') ) {
                        details.useVersion "1.0.1"
                    }
                }
            }
        }
    }

implementation

    void initState() {
        super.initState();
        initAction();
        StripeSource.setPublishableKey("mykey");
    }

flutter doctor

    Doctor summary (to see all details, run flutter doctor -v):
    [√] Flutter (Channel dev, v1.9.0, on Microsoft Windows [Version 10.0.18362.356], locale en-MY)

    [√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    [√] Android Studio (version 3.4)
    [√] VS Code (version 1.38.1)
    [√] Connected device (1 available)

    • No issues found!

**Comment by puneetsethi25** [comment]
I am having the same error. 
`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method setPublishableKey on channel stripe_payment)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      StripeSource.setPublishableKey (package:stripe_payment/stripe_payment.dart:23:14)
#2      StripePageState.initState (package:Savanton/pages/StripePage.dart:15:18)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#9      Element.updateChild (package:flutter/src/<…>
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method addSource on channel stripe_payment)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      StripeSource.addSource (package:stripe_payment/stripe_payment.dart:11:41)
<asynchronous suspension>
#2      StripePageState.build.<anonymous closure> (package:Savanton/pages/StripePage.dart:24:24)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
#6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
#7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:177:9)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src<…>`

**Comment by puneetsethi25** [comment]
minimum example to reporduce:
`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:stripe_payment/stripe_payment.dart';

class StripePage extends StatefulWidget {
  @override
  _StripePageState createState() => new _StripePageState();
}

class _StripePageState extends State<StripePage> {
  @override
  void initState() {
    super.initState();
    StripeSource.setPublishableKey("pk_test_key");
  }

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text('Plugin example app'),
        ),
        body: new Center(
          child: RaisedButton(
            child: Text("Add Card"),
            onPressed: () {
              print("Ready: ${StripeSource.ready}");
              StripeSource.addSource().then((String token) {
                _addSource(token);
              });
            },
          ),
        ),
      ),
    );
  }

  void _addSource(String token) {
    print("Token => $token");
  }
}`

**Comment by jonasbark** [comment]
I would need a whole Flutter project to reproduce. Dart Implemention is
only half of what it needs.

puneetsethi25 <notifications@github.com> schrieb am Sa., 14. Sep. 2019,
09:40:

**Comment by jonasbark** [comment]
Please try version 0.3.0.

**Comment by Nithinrnair** [comment]
i had same problem , and it was actually with my Appdelegate.swift , i accidentally replaced the code from firebase [ the code appears while adding ios app ] with the existing Appdelegate.swift code .. 

Wrong Implementation 

    import UIKit
    import Firebase
    import Flutter 
    
    @UIApplicationMain
    class AppDelegate: UIResponder, UIApplicationDelegate {
    
      var window: UIWindow?
    
      func application(_ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions:
        [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        FirebaseApp.configure()
        return true
      }
        
    }

RIGHT IMPLEMENTATION

import UIKit
import Flutter
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(_ application: UIApplication,didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        FirebaseApp.configure()
        GeneratedPluginRegistrant.register(with: self)

        

        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
}

**Comment by MuhammadAmin-Ibrohimov** [comment]
I am also having this error please help me with that 

I/flutter (14778): #1      MethodChannelStripe.initialise (package:stripe_platform_interface/src/method_channel_stripe.dart:53:5)
I/flutter (14778): <asynchronous suspension>
I/flutter (14778): #2      Stripe._initialise (package:flutter_stripe/src/stripe.dart:692:5)
I/flutter (14778): <asynchronous suspension>
I/flutter (14778): #3      Stripe.initPaymentSheet (package:flutter_stripe/src/stripe.dart:453:5)
I/flutter (14778): <asynchronous suspension>
I/flutter (14778): #4      _WalletState.makePayment.<anonymous closure> (package:e_commerce_app/pages/wallet.dart:172:17)
I/flutter (14778): <asynchronous suspension>
I/flutter (14778): #5      _WalletState.makePayment (package:e_commerce_app/pages/wallet.dart:166:7)
I/flutter (14778): <asynchronous suspension>


My payment function is here 


Future<void> makePayment(String amount) async {
    try {
      paymentintent = await createPaymentIntent(amount, 'INR');
      await Stripe.instance
          .initPaymentSheet(
              paymentSheetParameters: SetupPaymentSheetParameters(
                  paymentIntentClientSecret: paymentintent!['client_secret'],
                  style: ThemeMode.dark,
                  merchantDisplayName: "Muhammad"))
          .then((value) {});
      displayPaymentSheet(amount);
    } catch (e, s) {
      print("exception is there -->: $e$s");
    }
  }

  displayPaymentSheet(String amount) async {
    try {
      await Stripe.instance.presentPaymentSheet().then((value) async {
        showDialog(
            context: context,
            builder: (_) => const AlertDialog(
                  content: Column(
                    children: [
                      Row(
                        children: [
                          Icon(
                            Icons.check_circle,
                            color: Colors.green,
                          ),
                          Text("Payment Successfull")
                        ],
                      )
                    ],
                  ),
                ));

        paymentintent = null;
      }).onError((error, stackTrace) {
        print("Error is --> $error $stackTrace");
      });
    } on StripeException catch (e) {
      print("Error is: --> $e");
      showDialog(
          context: context,
          builder: (_) => const AlertDialog(
                content: Text("Cancelled"),
              ));
    } catch (e) {
      print('$e');
    }
  }

  createPaymentIntent(String amount, String currency) async {
    try {
      Map<String, dynamic> body = {
        'amount': calculateAmount(amount),
        'currency': currency,
        'payment_method_types[]': 'card'
      };
      var response = await http.post(
          Uri.parse("https://api.stripe.com/v1/payment_intents"),
          headers: {
            'Authorization': 'Bearer $secretKey',
            'Content-Type': 'application/x-www-form-urlencoded'
          },
          body: body);
      print("Payment intent Body --> ${response.body.toString()}");
      return jsonDecode(response.body);
    } catch (err) {
      print("err charging user: ${err.toString()}");
    }
  }

  calculateAmount(String amount) {
    final calculateAmount = (int.parse(amount) * 100);
    return calculateAmount.toString();
  }

Can anyone help me

**Comment by MuhammadAmin-Ibrohimov** [comment]
`Future<void> makePayment(String amount) async {
    try {
      paymentintent = await createPaymentIntent(amount, 'INR');
      await Stripe.instance
          .initPaymentSheet(
              paymentSheetParameters: SetupPaymentSheetParameters(
                  paymentIntentClientSecret: paymentintent!['client_secret'],
                  style: ThemeMode.dark,
                  merchantDisplayName: "Muhammad"))
          .then((value) {});
      displayPaymentSheet(amount);
    } catch (e, s) {
      print("exception is there -->: $e$s");
    }
  }

  displayPaymentSheet(String amount) async {
    try {
      await Stripe.instance.presentPaymentSheet().then((value) async {
        showDialog(
            context: context,
            builder: (_) => const AlertDialog(
                  content: Column(
                    children: [
                      Row(
                        children: [
                          Icon(
                            Icons.check_circle,
                            color: Colors.green,
                          ),
                          Text("Payment Successfull")
                        ],
                      )
                    ],
                  ),
                ));

        paymentintent = null;
      }).onError((error, stackTrace) {
        print("Error is --> $error $stackTrace");
      });
    } on StripeException catch (e) {
      print("Error is: --> $e");
      showDialog(
          context: context,
          builder: (_) => const AlertDialog(
                content: Text("Cancelled"),
              ));
    } catch (e) {
      print('$e');
    }
  }

  createPaymentIntent(String amount, String currency) async {
    try {
      Map<String, dynamic> body = {
        'amount': calculateAmount(amount),
        'currency': currency,
        'payment_method_types[]': 'card'
      };
      var response = await http.post(
          Uri.parse("https://api.stripe.com/v1/payment_intents"),
          headers: {
            'Authorization': 'Bearer $secretKey',
            'Content-Type': 'application/x-www-form-urlencoded'
          },
          body: body);
      print("Payment intent Body --> ${response.body.toString()}");
      return jsonDecode(response.body);
    } catch (err) {
      print("err charging user: ${err.toString()}");
    }
  }

  calculateAmount(String amount) {
    final calculateAmount = (int.parse(amount) * 100);
    return calculateAmount.toString();
  }`
