### ISSUE TITLE
You cannot create a charge with a PaymentMethod?

### ISSUE THREAD

**Issue by wyxcoder** [jonasbark/flutter_stripe_payment#39]
When I use the token to call stripe.Charge.create, I got error

You cannot create a charge with a PaymentMethod. Use the Payment Intents API instead

Any idea what is the problem?

**Comment by jonasbark** [comment]
how do you call "stripe.Charge.create"? which package is that? Context?

**Comment by wyxcoder** [comment]
That is how my current webapp works, on browser, I use https://js.stripe.com/v3/, collect stripe token. On server side, I call stripe.charge.create with the token to complete the purchase.
I tried to use the same backend to handle the purchase on Android.
It looks like this lib is using PaymentIntent which is the new way stripe created. I am still checking how to switch.

**Comment by wyxcoder** [comment]
Could you please add some flutter sample code for the whole flow to use this lib?
To use PaymentInent, It seems you need create client secret on server first and pass to client side and then collect client side info and submit on server side.

**Comment by jonasbark** [comment]
Please refer to the official docs - they include lots of examples also for the server side.

**Comment by HathTech** [comment]
tipsi-stripe returns token not payment id. 
Can you let me know the way to return the token and not payment id.

**Comment by jonasbark** [comment]
tipsi-stripe in the latest branch returns the exact same thing as flutter_stripe_payment.
