### ISSUE TITLE
MainActivity cannot be cast to io.flutter.app.FlutterActivity

### ISSUE THREAD

**Issue by vagrantrobbie** [jonasbark/flutter_stripe_payment#4]
Can this plugin work with non Kotlin projects?

I've added the kotlin version to my build script 
buildscript {
    ext.kotlin_version = '1.2.21'

and the path to my dependencies 
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

To make Kotlin plugins work and this has been fine so far.

But when I change my MainActivity extend from FlutterActivity to FlutterFragmentActivity I get a run time error
java.lang.ClassCastException: MainActivity cannot be cast to io.flutter.app.FlutterActivity

Any thoughts here? I'd like to use this plugin with Google Pay https://stripe.com/docs/google-pay and Apple Pay https://stripe.com/apple-pay

**Comment by jonasbark** [comment]
Kotlin is required for now.

From where does this crash come from? I guess not from this plugin as it expects a FlutterFragmentActivity?

Please note Google & Apple Pay support is not integrated at the moment. This might happen in the future.

**Comment by vagrantrobbie** [comment]
It does come from this plugin. I tried creating a new project using kotlin as well but was getting the same crash. I will keep digging to get this to work as I am hoping to branch off and integrate Apple and Google Pay

**Comment by jonasbark** [comment]
Did you find a solution?

**Comment by vagrantrobbie** [comment]
I'm still still getting the error at extending the FlutterFragmentActivity

![screen shot 2018-06-11 at 9 03 38 am](https://user-images.githubusercontent.com/19616846/41206335-83de1972-6d56-11e8-94b5-0ce284cea0a7.png)

Tried flutter clean. I shouldn't actually need a kotlin project to support the plugin, should I? both language work nicely along side each other was what I had read

**Comment by vagrantrobbie** [comment]
Argh. Sorry for wasting your time. I have found the problem.

Another plugin was conflicting with the Activity (flutterWebView). I have removed it and I can now use this plugin! Thanks!

**Comment by jonasbark** [comment]
Don't worry, thanks for letting me know! I'll open up a new issue on the Flutter WebView Plugin github - it should be compatible with whatever kind of activity.
