### ISSUE TITLE
'stripe_native/StripeNativePlugin.h' file not found

### ISSUE THREAD

**Issue by thewirelessguy** [jonasbark/flutter_stripe_payment#42]
I'm getting the following build error on iOS (Xcode 11):
`/Users/sm/FlutterProjects/passenger/ios/Runner/GeneratedPluginRegistrant.m:11:9: 'stripe_native/StripeNativePlugin.h' file not found`

**Comment by jonasbark** [comment]
Please add a minimal project for me to reproduce.

**Comment by jonasbark** [comment]
With version 0.3.1 I removed stripe_native dependency that caused problems with their dependencies. Can you please try again and report back?

Related commit:
https://github.com/jonasbark/flutter_stripe_payment/commit/972d4f7415a4b50bc1ca9f9d3473d376b2ef687c
