### ISSUE TITLE
Stripe Native causing built fail on iOS.

### ISSUE THREAD

**Issue by BasedMusa** [jonasbark/flutter_stripe_payment#43]
Getting this after updating to 0.3.0

[!] CocoaPods could not find compatible versions for pod "stripe_payment":
  In Podfile:
    stripe_payment (from `.symlinks/plugins/stripe_payment/ios`)

Specs satisfying the `stripe_payment (from `.symlinks/plugins/stripe_payment/ios`)` dependency were found, but they required a higher minimum deployment target.
Tried running pod install and pod update. Same error message.

I am on CocoaPods 1.8.1

Help would be much appreciated.

**Comment by jonasbark** [comment]
It's exactly what it says. stripe_payment requires a minimum deployment target of 11.0: https://github.com/jonasbark/flutter_stripe_payment/blob/master/ios/stripe_payment.podspec#L20

https://www.google.com/search?q=xcode+update+deployment+target

**Comment by AirborneEagle** [comment]
This ticket lead me to the solution to my issue as well. 
I will leave this link here.
this is how you can update the ios target
https://flutter.dev/docs/deployment/ios#review-xcode-project-settings

**Comment by rxalimurad** [comment]
> 

> 

> 

> 

> 

> 

> 

> 

>
