### ISSUE TITLE
Google pay fails with OR-IDL-01 in live environment

### ISSUE THREAD

**Issue by ayushin** [jonasbark/flutter_stripe_payment#49]
Another thing: I seem to be having problems with Google Pay when I use the live key, but it works with test key. (Very weird as I'd think Google Pay doesn't know about stripe keys).

In live environment i get: OR-IDL-01 and in test environment it just works.

Any clues?

**Comment by ayushin** [comment]
`D/AndroidRuntime(12816): Shutting down VM
E/AndroidRuntime(12816): FATAL EXCEPTION: main
E/AndroidRuntime(12816): Process: io.aahi.eat, PID: 12816
E/AndroidRuntime(12816): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13873, result=1, data=Intent { (has extras) }} to activity {io.aahi.eat/io.aahi.eat.MainActivity}: java.lang.IllegalArgumentException: Unsupported value: Intent { (has extras) }
E/AndroidRuntime(12816): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
E/AndroidRuntime(12816): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
E/AndroidRuntime(12816): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(12816): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(12816): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(12816): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/AndroidRuntime(12816): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(12816): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(12816): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(12816): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12816): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(12816): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(12816): Caused by: java.lang.IllegalArgumentException: Unsupported value: Intent { (has extras) }
E/AndroidRuntime(12816): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/AndroidRuntime(12816): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/AndroidRuntime(12816): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/AndroidRuntime(12816): 	at de.jonasbark.stripepayment.StripePaymentPlugin.onActivityResult(StripePaymentPlugin.kt:232)
E/AndroidRuntime(12816): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
E/AndroidRuntime(12816): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
E/AndroidRuntime(12816): 	at io.flutter.app.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:137)
E/AndroidRuntime(12816): 	at android.app.Activity.dispatchActivityResult(Activity.java:7454)
E/AndroidRuntime(12816): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
E/AndroidRuntime(12816): 	... 11 more
I/Process (12816): Sending signal. PID: 12816 SIG: 9
`

Now I get this consistently in all environments. Weird it all worked a few times! @jnblanchard  any clue?

**Comment by jonasbark** [comment]
Are you sure you're using the newest version?
The mentioned line at https://github.com/jonasbark/flutter_stripe_payment/blob/master/android/src/main/kotlin/de/jonasbark/stripepayment/StripePaymentPlugin.kt#L232 does not contain anything.

**Comment by jonasbark** [comment]
were you using the version from https://github.com/jonasbark/flutter_stripe_payment/pull/47 ?

**Comment by ayushin** [comment]
I'm using the PR47.
`
                AutoResolveHelper.RESULT_ERROR -> {
                    AutoResolveHelper.getStatusFromIntent(data)?.let {
                        currentResult?.error("Error", it.statusMessage, data)
                    }
                }
`
Will try with master right now... hold on

**Comment by ayushin** [comment]
`E/AndroidRuntime(13965): 	at de.jonasbark.stripepayment.StripePaymentPlugin.onActivityResult(StripePaymentPlugin.kt:232)
` same story

**Comment by jonasbark** [comment]
Can you check latest master? You'll still receive an error from Google, but the Flutter part won't error out anymore

**Comment by ayushin** [comment]
OK, that fixes the crash but looses the error message. I just get "Error" - not very useful!

`e = {PlatformException} PlatformException(Error, null, null)
 code = "Error"
 message = null
 details = null`
