### ISSUE TITLE
Application crashes after install

### ISSUE THREAD

**Issue by CheeseNPort** [jonasbark/flutter_stripe_payment#5]
Just after including this package in the pubspec.yaml file like this:

stripe_payment: "^0.0.6"

Whenever the application starts, it immediately crashes. Here is the log. If I remove it from the pubspec file, the application goes back to working as it should.

Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       3.2s
Resolving dependencies...                                   17.4s
Running 'gradlew assembleDebug'...                          48.1s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                  2.4s

**Comment by jonasbark** [comment]
Did you see this?

> Please be aware that your main activity must extend from FlutterFragmentActivity. Otherwise the Android dialog would've looked very nasty.

**Comment by jonasbark** [comment]
If you did, please provide the crash log information from your android device. What you showed me are just some log entries regarding installation.

**Comment by CheeseNPort** [comment]
I had indeed missed that, but extending from that yield's its own problems, see the log below. I read in a couple of places about removing the @override which I tried.

Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       0.9s
Resolving dependencies...                                    1.6s
Running 'gradlew assembleDebug'...
C:\Users\mike\source\repos\app1android\app\src\main\java\com\exampleapp1\MainActivity.java:8: error: cannot find symbol
public class MainActivity extends FlutterFragmentActivity {
                                  ^
  symbol: class FlutterFragmentActivity
C:\Users\mike\source\repos\app1android\app\src\main\java\com\exampleapp1\MainActivity.java:9: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\Users\mike\source\repos\app1android\app\src\main\java\com\exampleapp1\MainActivity.java:11: error: cannot find symbol
    super.onCreate(savedInstanceState);
    ^
  symbol:   variable super
  location: class MainActivity
C:\Users\mike\source\repos\app1android\app\src\main\java\com\exampleapp1\MainActivity.java:12: error: incompatible types: MainActivity cannot be converted to PluginRegistry
    GeneratedPluginRegistrant.registerWith(this);
                                           ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Gradle build failed: 1

**Comment by jonasbark** [comment]
That pretty much means you're missing the import statement of FlutterFragmentActivity class in your MainActivity.java.

**Comment by CheeseNPort** [comment]
Oh yeah thanks that did the trick! Probably should have opened the application in Android Studio to see the build results, I was just in VS Code.
