### ISSUE TITLE
conflict library with gogle services

### ISSUE THREAD

**Issue by sante85** [jonasbark/flutter_stripe_payment#50]
I have this problem
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.3.1
  ,2.3]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.nimbusds:nimbus-jose-jwt:7.8 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2
  .3.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.nimbusds:nimbus-jose-jwt@7.8
  -- Project 'app' depends onto net.minidev:json-smart@2.3
  -- Project 'app' depends on project 'stripe_payment' which depends onto com.stripe:stripe-android@11.1.4
  -- Project 'app' depends onto com.stripe:stripe-3ds2-android@2.0.5
  -- Project 'app' depends onto com.stripe:stripe-android@11.1.4

  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle task assembleDebug failed with exit code 1

pubspec.yml

shared_preferences: 0.5.2+1
  firebase_core: ^0.4.0
  firebase_messaging: 5.1.5
  flutter_local_notifications: 0.8.3
  stripe_payment: 0.3.1

build.gradle
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath 'com.google.gms:google-services:4.3.2'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

app/build.gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def appName = localProperties.getProperty('flutter.appName')
if (appName == null) {
    appName = ''
}

def flutterAppId = localProperties.getProperty('flutter.appId')
if (flutterAppId == null) {
    flutterAppId = ''
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '4'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '0.0.4'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId flutterAppId
        minSdkVersion 19
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            resValue "string", "app_name", appName
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation "androidx.core:core:1.0.1"
}

apply plugin: 'com.google.gms.google-services'

**Comment by ayushin** [comment]
i have the same problem - looks like some dependencies version clash, trying to figure it out now

**Comment by ayushin** [comment]
can you try:
`./gradlew app:dependencies`
?

**Comment by sante85** [comment]
I have tryed. Same error

Il gio 3 ott 2019, 10:52 Alexis Yushin <notifications@github.com> ha
scritto:

**Comment by ayushin** [comment]
i had this problem because i had too many conflicting dependencies, try removing them one by one

**Comment by sante85** [comment]
I have firebase_messaging.
It Is not possibile remove.

Il gio 3 ott 2019, 14:07 Alexis Yushin <notifications@github.com> ha
scritto:

**Comment by ayushin** [comment]
I do too:

app/build.gradle:
`
...
dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.google.firebase:firebase-messaging:20.0.0'
}
...
`

build.gradle:
`
buildscript {
    ext.kotlin_version = '1.3.50'

    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.1'
        classpath 'com.google.gms:google-services:4.3.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

`

**Comment by jonasbark** [comment]
Can you share a minimal project where this is reproducible?

**Comment by sante85** [comment]
Yes

Il ven 4 ott 2019, 11:57 jonasbark <notifications@github.com> ha scritto:

**Comment by sante85** [comment]
https://drive.google.com/drive/folders/1kkVvEpNHQ27YH4skL0lUd8zbiMbAS6-y?usp=sharing

Il giorno ven 4 ott 2019 alle ore 15:05 Sante Stanisci <s.sante85@gmail.com>
ha scritto:

**Comment by sante85** [comment]
hi, any news?

**Comment by jonasbark** [comment]
Hi!
As stated in your initial error message, please add this to your androids build.gradle file:
```googleServices { disableVersionCheck = false }```
Related: https://github.com/invertase/react-native-firebase/issues/1676

In your test project I still got dependency errors related to androidx, but thats not the plugins fault anymore.

**Comment by sante85** [comment]
work fine.

i have another question. sca process is full implemented?

Thank you

Il giorno sab 5 ott 2019 alle ore 23:44 jonasbark <notifications@github.com>
ha scritto:

**Comment by sante85** [comment]
not run

defaultConfig {
    multiDexEnabled true
..

}

googleServices.disableVersionCheck = true


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-media-compat:26.1.0' is set to compileOnly/provided which is not supported

* Try:
Run with --stacktrace option to get the stack trace. Run with --info
or --debug option to get more log output. Run with --scan to get full
insights.

* Get more help at https://help.gradle.org


Il giorno dom 6 ott 2019 alle ore 09:05 Sante Stanisci <s.sante85@gmail.com>
ha scritto:

**Comment by sante85** [comment]
in my application app crash, without any error

Il giorno dom 6 ott 2019 alle ore 09:28 Sante Stanisci <s.sante85@gmail.com>
ha scritto:

**Comment by sante85** [comment]
if in your example add

app/build.gradle

googleServices.disableVersionCheck = true

pubspec.yml

stripe_payment: 0.3.1
firebase_core: ^0.4.0
firebase_messaging: 5.1.5

-------------------

error
Launching lib/main.dart on MYA L11 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Finished with error: Gradle task assembleDebug failed with exit code 1



Il giorno dom 6 ott 2019 alle ore 09:41 Sante Stanisci <s.sante85@gmail.com>
ha scritto:
