### ISSUE TITLE
isReadyToPay feature required for Google Pay and Apple Pay live integrations

### ISSUE THREAD

**Issue by ayushin** [jonasbark/flutter_stripe_payment#51]
Both Google and Apple require that we only display the "pay" button when it is available and that has to be checked via isReadyToPay (Google) or similar Apple

**Comment by jonasbark** [comment]
we'll have that once https://github.com/jonasbark/flutter_stripe_payment/pull/48/files is merged

**Comment by jonasbark** [comment]
1.0.0 is now live with that feature
