### ISSUE TITLE
app integration fail

### ISSUE THREAD

**Issue by sante85** [jonasbark/flutter_stripe_payment#52]
app/build.gradle

defaultConfig {
        multiDexEnabled true
....
}

googleServices.disableVersionCheck = true

pubspec.yml

stripe_payment: 0.3.1
firebase_core: ^0.4.0
firebase_messaging: 5.1.5

if you test in your example project,

build fail

**Comment by sante85** [comment]
i'm not know, if in your library there are conflic with androidx or other libs

**Comment by sante85** [comment]
how to debug your code in my application??

**Comment by sante85** [comment]
because i want resolve problem, for other developers

**Comment by jonasbark** [comment]
I checked against the test project from you.
I needed to do the following changes:
- update Kotlin in android/build.gradle
- convert the project to AndroidX https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility
- enable multidex

Building the APK works fine. If it doesn't work for you, then at least tell me the error messages. It will very likely not be the plugins fault so you'd better consult with Stackoverflow instead.

**Comment by sante85** [comment]
update Kotlin in android/build.gradle which version?

ext.kotlin_version = '1.3.41'

enable multidex already ok

convert the project to AndroidX

implementation "androidx.core:core:1.1.0"


it install, but at run crash.

i attach a edited project, with you directives.

https://drive.google.com/drive/folders/1kkVvEpNHQ27YH4skL0lUd8zbiMbAS6-y?usp=sharing


Il giorno dom 6 ott 2019 alle ore 13:05 jonasbark <notifications@github.com>
ha scritto:

**Comment by jonasbark** [comment]
Looks like you didn't follow the links I posted.
https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility
Step 3 **and** it's also described in https://github.com/jonasbark/flutter_stripe_payment#android

It still crashes but it's because you didn't configure Kotlin correctly. So again: use Stackoverflow instead for those questions. They have nothing to do with this plugin.

**Comment by jonasbark** [comment]
And for the future: Provide crash logs or build logs - otherwise no one will be able to help you.

**Comment by sante85** [comment]
Hi,

I have checked all

https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility
Step 3 *and* it's also described in
https://github.com/jonasbark/flutter_stripe_payment#android

are already ok.

"It still crashes but it's because you didn't configure Kotlin correctly"

how to configure kotlin correctly?

Best regards

Il giorno dom 6 ott 2019 alle ore 19:13 jonasbark <notifications@github.com>
ha scritto:

**Comment by sante85** [comment]
you have tried my project?

because i have set every parameter, but app run and crash.

please can help me to resolve this problem?

best regards

Il giorno mer 9 ott 2019 alle ore 15:35 Sante Stanisci <s.sante85@gmail.com>
ha scritto:

**Comment by jonasbark** [comment]
https://github.com/jonasbark/flutter_stripe_payment/issues/52#issuecomment-538767557

**Comment by sante85** [comment]
build log 
Launching lib/main.dart on MYA L11 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:42137/2z6oZa7Pn5U=/ws

**Comment by sante85** [comment]
i not have understand if in android resource i could add res as your example.

i add only dep in pub spec.yml

**Comment by sante85** [comment]
if i add only

api 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50'
    api 'com.stripe:stripe-android:11.1.4'
    implementation 'com.google.android.gms:play-services-wallet:18.0.0'

project run
