### ISSUE TITLE
Future is not returned 

### ISSUE THREAD

**Issue by algirdasmac** [jonasbark/flutter_stripe_payment#55]
Hello,

I am really loving this plugin, but there is one thing, that does not allow me to fully separate business logic and views in BLoC pattern - when user clicks on "Cancel" button there is no future returned in method StripePayment.addSource().

You can try yourself, code is really simple:
```dart
String paymentMethodId = await StripePayment.addSource();
print(paymentMethodId);
```
Try cancelling - nothing is returned and printed.

The same goes for StripePayment.setupPayment and StripePayment.confirmPayment, if additional SCA steps is needed and user presses cancel.

I worked around the problem, but the solution is not so elegant, and it involves adding some business logic to views.

Thanks again for the plugin, I hope this could be resolved!

**Comment by jonasbark** [comment]
Hi! Can you try this package with the dev-branch?
It's a full rewrite based on tipsi-stripe and should fix at least cancelling setupPayment + confirmPayment. I'll have a look at addSource later on.

**Comment by algirdasmac** [comment]
I tried dev branch - looks like a very big improvement! So much more control, I love it!

Basically now futures are returned, even if I press cancel button. Although errors are unhandled:
`
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(cancelled, Cancelled by user, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
<asynchronous suspension>
#2      StripePayment.paymentRequestWithCardForm (package:stripe_payment/src/stripe_payment.dart:92:34)
`
try catch solves this problem for me, so I do not see it as a critical thing.
Thanks, will be waiting for official plugin release to master!

**Comment by algirdasmac** [comment]
Spoke a little bit too early.
I try adding new payment method:
```dart
Token token = await StripePayment.paymentRequestWithCardForm(CardFormPaymentRequest());
```
Token does not have an ID:
```dart
print(token.tokenId); // null
print(token.card.cardId); // null
```

**Comment by jonasbark** [comment]
You're right - I fixed that in the latest commit.

**Comment by algirdasmac** [comment]
> Hi again,
> 
> StripePayment.confirmSetupIntent(intent) throws an error:
> `type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'`
> 
> To me it looks like the problem is here, when you are converting json to StripeIntentResult:
> 
> ```dart
>   factory SetupIntentResult.fromJson(Map<String, dynamic> json) {
>     return SetupIntentResult(
>       status: json['status'],
>       setupIntentId: json['setupIntentId'],
>       paymentIntentId: json['paymentIntentId'],
>     );
>   }
> ```
> 
> You expect to get json of type Map<String, dynamic>, but:
> 
> ```dart
>   static Future<SetupIntentResult> confirmSetupIntent(PaymentIntent intent) async {
>     final result = await _channel.invokeMethod('confirmSetupIntent', intent.toJson());
>     return SetupIntentResult.fromJson(result);
>   }
> ```
> 
> result is probably not a Map<String, dynamic>.

Just tested changing this:
```dart
factory SetupIntentResult.fromJson(Map<String, dynamic> json) {
    return SetupIntentResult(
      status: json['status'],
      setupIntentId: json['setupIntentId'],
      paymentIntentId: json['paymentIntentId'],
    );
  }
```
to this:
```dart
factory SetupIntentResult.fromJson(Map<dynamic, dynamic> json) {
    return SetupIntentResult(
      status: json['status'],
      setupIntentId: json['setupIntentId'],
      paymentIntentId: json['paymentIntentId'],
    );
  }
```

And now method works

**Comment by jonasbark** [comment]
Thanks! Next time feel free to make a pull request.
Apart from that, did you have any issues with the dev branch?

**Comment by jonasbark** [comment]
Version 1.0 is now released

**Comment by algirdasmac** [comment]
This issue needs to be reopened for Android - future is not returned if you dismiss addPaymentMethod dialog.

**Comment by algirdasmac** [comment]
also another error on android when using confirmSetupIntent:
I/flutter (19379): PlatformException(invalidRequest, Unrecognized request URL (POST: /v1/setup_intents//confirm). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/., null)

**Comment by jonasbark** [comment]
Regarding confirmSetupIntent: are you sure your parameter (PaymentIntent) contains a non-empty paymentMethod and paymentMethodId?

**Comment by algirdasmac** [comment]
> Regarding confirmSetupIntent: are you sure your parameter (PaymentIntent) contains a non-empty paymentMethod and paymentMethodId?

Sorry, my bad!
