### ISSUE TITLE
Problem with fcm notifications and stripe plugin

### ISSUE THREAD

**Issue by rodrigocanepa** [jonasbark/flutter_stripe_payment#57]
Hey, flutter stripe payment is a good plugin but I have some problems with the Firebase Notifications, because without the stripe plugin the notifications are working well, but when I add the plugin the notifications are not working when the app is terminated and the console return this exception:

E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): kotlin.TypeCastException: null cannot be cast to non-null type androidx.fragment.app.FragmentActivity
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at de.jonasbark.stripepayment.StripePaymentPlugin$Companion.registerWith(StripePaymentPlugin.kt:16)
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at de.jonasbark.stripepayment.StripePaymentPlugin.registerWith(Unknown Source:2)
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:18)
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at com.apps.scode.flutter_notifications.Application.registerWith(Application.java:18)
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.startBackgroundIsolate(FlutterFirebaseMessagingService.java:164)
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.onMethodCall(FirebaseMessagingPlugin.java:134)
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:645)
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at android.os.MessageQueue.next(MessageQueue.java:386)
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at android.os.Looper.loop(Looper.java:175)
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/MethodChannel#plugins.flutter.io/firebase_messaging(14533): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/        (14533): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
E/flutter (14533): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, null cannot be cast to non-null type androidx.fragment.app.FragmentActivity, null)

**Comment by jonasbark** [comment]
Did you follow https://pub.dev/packages/stripe_payment the Readme closely?
> Please be aware that your main activity must extend from FlutterFragmentActivity. Otherwise the Android dialog would've looked very nasty.

You could also try the dev branch of this plugin. With that branch you will no longer need to extend from FlutterFragmentActivity.

**Comment by rodrigocanepa** [comment]
Yes, and the Stripe plugin is working well, the problem is when I try to join the fcm notifications with the Stripe plugin, for some reason I have those exceptions, maybe the problem is the part "registerWith" because for the notifications I need create a new java class called Application wich extends from FlutterApplication and then I had to change the android manifest. By the way, how can I try with the dev branch?

**Comment by jonasbark** [comment]
Check out https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

**Comment by jonasbark** [comment]
Ought to be fixed with https://github.com/jonasbark/flutter_stripe_payment/pull/53
