### ISSUE TITLE
Undefined name 'StripeSource' in 0.3.1

### ISSUE THREAD

**Issue by jsdjayanga** [jonasbark/flutter_stripe_payment#58]
According to the instructions, StripeSource.addSource() has to be called to add a new card. But class StripeSource is missing in the source. It was renamed to StripePayment in d7024a2f5921a32c063e54dfe5a3c15249432608

**Comment by jonasbark** [comment]
Fixed with https://github.com/jonasbark/flutter_stripe_payment/pull/53
