### ISSUE TITLE
Unable to find com.gettipsi.stripe.OpenBrowserActivity

### ISSUE THREAD

**Issue by olihop** [jonasbark/flutter_stripe_payment#68]
Using flutter 10.14, I'm unable to get the example working. The app loads fine in an android emulator, and creating a payment method and some other functions work.  Tapping "Create Source," however, causes it to crash with the following:

`E/AndroidRuntime( 5463): FATAL EXCEPTION: main
E/AndroidRuntime( 5463): Process: de.jonasbark.stripepaymentexample, PID: 5463
E/AndroidRuntime( 5463): android.content.ActivityNotFoundException: Unable to find explicit activity class {de.jonasbark.stripepaymentexample/com.gettipsi.stripe.OpenBrowserActivity}; have you declared this activity in your AndroidManifest.xml?
E/AndroidRuntime( 5463):        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2049)
E/AndroidRuntime( 5463):        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1709)
E/AndroidRuntime( 5463):        at android.app.Activity.startActivityForResult(Activity.java:5192)
E/AndroidRuntime( 5463):        at android.app.Activity.startActivityForResult(Activity.java:5150)
E/AndroidRuntime( 5463):        at android.app.Activity.startActivity(Activity.java:5521)
E/AndroidRuntime( 5463):        at android.app.Activity.startActivity(Activity.java:5489)
E/AndroidRuntime( 5463):        at com.gettipsi.stripe.StripeModule$10.onSuccess(StripeModule.java:411)
E/AndroidRuntime( 5463):        at com.gettipsi.stripe.StripeModule$10.onSuccess(StripeModule.java:389)
E/AndroidRuntime( 5463):        at com.stripe.android.ApiOperation.onPostExecute(ApiOperation.java:32)
E/AndroidRuntime( 5463):        at com.stripe.android.ApiOperation.onPostExecute(ApiOperation.java:11)
E/AndroidRuntime( 5463):        at android.os.AsyncTask.finish(AsyncTask.java:755)
E/AndroidRuntime( 5463):        at android.os.AsyncTask.access$900(AsyncTask.java:192)
E/AndroidRuntime( 5463):        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
E/AndroidRuntime( 5463):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 5463):        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 5463):        at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 5463):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5463):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 5463):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**Comment by jonasbark** [comment]
Thanks! 1.0.4 was just uploaded with a fix.
