### ISSUE TITLE
Internationalization the dilogs 

### ISSUE THREAD

**Issue by Abgaryan** [jonasbark/flutter_stripe_payment#7]

**Comment by andreabtis** [comment]
Why we can't custom the dialog? :(

**Comment by jonasbark** [comment]
I'm happy to accept pull requests!

**Comment by panuavakul** [comment]
@andreabtis Custom dialog might be really hard now, since I tried to wrap the whole widget in a native platform and was able to use the Stripe card input part with my own Flutter widget, but due to 
https://github.com/flutter/flutter/issues/19718
I was not able to get the keyboard to work.
