### ISSUE TITLE
Generate payment method with Apple Pay and G Pay.

### ISSUE THREAD

**Issue by jocelyngirard** [jonasbark/flutter_stripe_payment#70]
Hello @jonasbark,

Possible to implement a Stripe's `paymentMethod` from native pay to be fully SCA compliant ?
Is it on your implementation roadmap ?

I can try to implement it for Android, but I am not comfortable with Objective-C for the iOS side.

Thanks for your work.

**Comment by jonasbark** [comment]
Can you tell me what exactly is missing here for full SCA compliance?

**Comment by jocelyngirard** [comment]
Ok. My bad, I can create a `paymentMethod` from a card `token`. 

Note to myself: RTFM 🤓.
