### ISSUE TITLE
Unable to run pub get

### ISSUE THREAD

**Issue by Khaoz-Topsy** [jonasbark/flutter_stripe_payment#72]
Hi I am currently on the Flutter master branch, as soon as I added the package and save the pubspec.yaml file I get the following error:

`Couldn't read file LocalFile: 'D:\Flutter\.pub-cache\hosted\pub.dartlang.org\stripe_payment-1.0.4\android\src\main\kotlin\de\jonasbark\stripepayment\StripePaymentPlugin.kt' even though it exists. Please verify that this file has read permission and try again.`

I navigated to the folder and there is no Kotlin folder
I am hoping that it is a simple fix 😅

**Comment by Khaoz-Topsy** [comment]
Created a new Flutter App, added `stripe_payment: 1.0.4` and got the same issue. So it might be my Flutter installation 😞

**Comment by jonasbark** [comment]
Try deleting your .pub-cache directory altogether?

**Comment by Khaoz-Topsy** [comment]
Tried on a different machine and it works, thanks for the help 😅
