### ISSUE TITLE
Token Object not returned in paymentRequestWithCardForm

### ISSUE THREAD

**Issue by gouthamkumar253** [jonasbark/flutter_stripe_payment#79]
Hi there. Thanks a lot for this plugin and it is really great for Payment Intents and helped me a lot.
I'm trying to create a token for a new card using paymentRequestWithCardForm method. The method, however, does not return a token object (as it is supposed to according to the documentation in Tipsi) and only returns a Card object and paymentMethod object. Also, the card number in the object is null so unable to use that for creating a token. I don't know if I'm doing it wrong, so can you help me out?

**Comment by jonasbark** [comment]
1. Why do you still think you didn't create a token when creating a payment method?
2. I'm sure the Stripe support is happy to help!

**Comment by gouthamkumar253** [comment]
@jonasbark I'm trying to use the `paymentMethod` object which is the only response returned.

`{created: 1572363681.0, id: pm_1FYwouIVB1qNZTGAoOipTkcX, livemode: false, type: card, billingDetails: {address: {country: US}}, card: {addressLine1: null, addressLine2: null, brand: visa, country: US, expMonth: 2, expYear: 2022, funding: credit, last4: 4242}}`

In this, I considered `id` as the token to be used. As I don't see any separate token object returned.
When using this as token I am getting an error as `payment method id cannot be used as token` please advise.

**Comment by gouthamkumar253** [comment]
Hi, I figured it out and thanks for taking the time to explain it to me. Can you just tell me what's the difference between confirmPaymentIntent and authenticatePaymentIntent?

**Comment by jamesdixon** [comment]
@gouthamkumar253 can you let me know what your solution was? this is also a bit confusing

**Comment by gouthamkumar253** [comment]
@jamesdixon  kindly refer to this blog
https://digiryte.com/blog/posts/online-payments-made-easier-by-digiryte-by-flutter-and-ruby-on-rails
And to answer your question, u don't need a token at all to save or attach a card to your customer.
