### ISSUE TITLE
Cannot find symbols

### ISSUE THREAD

**Issue by herrmartell** [jonasbark/flutter_stripe_payment#80]
On a completely blank, new project, adding this package gives lots of errors. I updated gradle, stripe android sdk to latest version, but I keep getting these errors:

> C:\Users\herrm\scoop\apps\flutter\current\.pub-cache\hosted\pub.dartlang.org\stripe_payment-1.0.5\android\src\main\java\com\gettipsi\stripe\util\Converters.java:89: error: cannot find symbol
    result.putString("cvc", card.getCVC() );
                                ^
  symbol:   method getCVC()
  location: variable card of type Card
C:\Users\herrm\scoop\apps\flutter\current\.pub-cache\hosted\pub.dartlang.org\stripe_payment-1.0.5\android\src\main\java\com\gettipsi\stripe\StripeModule.java:150: error: cannot find symbol
        new TokenCallback() {
            ^
  symbol:   class TokenCallback
  location: class StripeModule
C:\Users\herrm\scoop\apps\flutter\current\.pub-cache\hosted\pub.dartlang.org\stripe_payment-1.0.5\android\src\main\java\com\gettipsi\stripe\StripeModule.java:174: error: cannot find symbol
        new TokenCallback() {
            ^
  symbol:   class TokenCallback
  location: class StripeModule
C:\Users\herrm\scoop\apps\flutter\current\.pub-cache\hosted\pub.dartlang.org\stripe_payment-1.0.5\android\src\main\java\com\gettipsi\stripe\StripeModule.java:389: error: cannot find symbol
    mStripe.createSource(sourceParams, new SourceCallback() {
                                           ^
  symbol:   class SourceCallback
  location: class StripeModule
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\herrm\scoop\apps\flutter\current\.pub-cache\hosted\pub.dartlang.org\stripe_payment-1.0.5\android\src\main\java\com\facebook\react\bridge\ReadableMap.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

> FAILURE: Build failed with an exception.

> * What went wrong:
Execution failed for task ':stripe_payment:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

> * Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

> * Get more help at https://help.gradle.org

> BUILD FAILED in 34s
> Finished with error: Gradle task assembleDebug failed with exit code 1

Can anyone be so kind to help me? Thanks

**Comment by furyou81** [comment]
Hi,

I did this and it works for me:

- in android/gradle.properties  add android.useAndroidX=true and android.enableJetifier=true
- in "android/app/build.gradle" set "multiDexEnabled true"
- in "android/app/build.gradle" set "minSdkVersion 21"
- in android/build.gradle set dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'com.google.gms:google-services:4.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
- in android/build.gradle set ext.kotlin_version = '1.3.0'

**Comment by jonasbark** [comment]
Yes, the kotlin gradle plugin must be enabled for this to work!

**Comment by herrmartell** [comment]
Sorry but I still cannot fix this. I followed all the steps suggested by @furyou81 but now I get these:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':stripe_payment:compileDebugAidl'.
> > In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.3.1
>   ,2.3]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
> 
>   Dependency failing: com.nimbusds:nimbus-jose-jwt:7.9 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2
>   .3.
> 
>   The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
>   ifact with the issue.
>   -- Project 'app' depends on project 'stripe_payment' which depends onto com.stripe:stripe-android@12.2.0
>   -- Project 'app' depends on project 'stripe_payment' which depends onto net.minidev:json-smart@2.3
>   -- Project 'app' depends on project 'stripe_payment' which depends onto com.nimbusds:nimbus-jose-jwt@7.9
>   -- Project 'app' depends on project 'stripe_payment' which depends onto com.stripe:stripe-3ds2-android@2.1.3
> 
>   For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
>   endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
>   github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
>   uild.gradle file.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 5s
> Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by JaimilPatel** [comment]
I have still facing error which was metioned by @herrmartell 
https://github.com/jonasbark/flutter_stripe_payment/issues/80#issue-515727621
