### ISSUE TITLE
Authentication of PaymentIntents

### ISSUE THREAD

**Issue by HarshithaCSE** [jonasbark/flutter_stripe_payment#83]
I'm trying to authenticate a payment intent using the authenticatePaymentIntent method. I receive the response as 

> {paymentIntentId: pi_1FaNUAIVB1qNZTGAw6z2Qdgt, status: requires_confirmation}

I'm not able to enter any authentication flow such as OTP or address verification. Is this the expected behaviour? If so, then how will I perform OTP authentication for SCA required transactions?

**Comment by jonasbark** [comment]
All I did was port over tipsi-stripe to Flutter, so you might be able to find your answers there:
https://github.com/tipsi/tipsi-stripe/tree/experimental-connect/website/docs-md
