### ISSUE TITLE
request failed-android

### ISSUE THREAD

**Issue by haneensaadeh1994** [jonasbark/flutter_stripe_payment#84]
Transaction declined: invalid payment method. Learn more [OR-CCSEH-05]

**Comment by jonasbark** [comment]
Context?

**Comment by haneensaadeh1994** [comment]
`  StripePayment.setOptions(StripeOptions(
        publishableKey: "pk_test_LNsDQJbtyJ2s8xt2TseXo3v300H3eLNwHz",
        merchantId: "Test",
        androidPayMode: 'test'));`

`   StripePayment.paymentRequestWithNativePay(
                              androidPayOptions: AndroidPayPaymentRequest(
                                total_price: "1.20",
                                currency_code: "USD",
                              ),
                              applePayOptions: ApplePayPaymentOptions(
                                countryCode: 'US',
                                currencyCode: 'USD',
                                items: [
                                  ApplePayItem(
                                    label: 'Test',
                                    amount: '13',
                                  )
                                ],
                              ),
                            ).then((token) {
                              setState(() {
                                _scaffoldKey.currentState.showSnackBar(SnackBar(
                                    content:
                                        Text('Received ${token.tokenId}')));
                                _paymentToken = token;
                              });
                            }).catchError((e) {});`

**Comment by jonasbark** [comment]
Please consult with Google or the Stripe Support.
