### ISSUE TITLE
create source from payment method

### ISSUE THREAD

**Issue by jamesdixon** [jonasbark/flutter_stripe_payment#90]
Hi, I'm trying to create a card source from a credit card the user enters. I've tried the following:

```dart
StripePayment.paymentRequestWithCardForm(
  CardFormPaymentRequest(),
).then((paymentMethod) {
  StripePayment.createSourceWithParams(
    SourceParams(
      type: 'card',
      card: paymentMethod.card,
    ),
  ).then((source) {
    print(source);
  }).catchError((err) {
    print(err);
  });
}).catchError((err) {
  print(err);
});
```

Unfortunately, I keep getting the following error:

`The payment method `card` requires the parameter: card[number].`

A few things:

1. I see that `paymentMethod.card` has no number. Why is this? 
2. `SourceParams` requires `returnURL` in the library but in the Tipsi docs, it indicates that this is only if they need to authorize the payment. In my case, I'm just trying to create a payment method for future use.

Am I doing this all wrong? I know PaymentIntent is the new API but the dev I'm working with just wants the id of the source.

Thanks in advance.

**Comment by gouthamkumar253** [comment]
@jamesdixon you can't create source from  the card object in the payment method because it's just an instance of tokenized information of the card stored in stripe. Kindly refer to the blog for detailed instructions
https://digiryte.com/blog/posts/online-payments-made-easier-by-digiryte-by-flutter-and-ruby-on-rails

**Comment by jonasbark** [comment]
@jamesdixon did the answer from @gouthamkumar253 clear that up?

**Comment by jamesdixon** [comment]
@gouthamkumar253 thank you for the article. very helpful!
