### ISSUE TITLE
Credit card dialog doesn't return credit card number on iOS

### ISSUE THREAD

**Issue by theswerd** [jonasbark/flutter_stripe_payment#93]
The credit card dialog returns a card with incomplete data.
The data is missing the card number.

**Comment by jonasbark** [comment]
Works as intended. The credit card is added to Stripe and you will not be able to see anything from the initial card number expect the last four numbers. 
Please refer to Stripes documentation ;)

**Comment by gouthamkumar253** [comment]
@theswerd check this out
https://medium.com/flutter-community/flutter-card-payments-made-easy-with-stripe-and-ruby-on-rails-50d78ac056ce
