### ISSUE TITLE
Plugin not compatible with FlutterFragmentActivity

### ISSUE THREAD

**Issue by NickCullen** [jonasbark/flutter_stripe_payment#97]
Hello,

I have an app (Android) that worked when my application inherited from FlutterActivity but since adding local_auth and having to change it to a FlutterFragmentActivity I have found out the payments have stopped working. 

I am just wondering what the use case of explicitly casting to FlutterActivity within this plugin is? 

Both commonly inherit from android.app.Activity, would the plugin still work if being cast to Activity instead of explicitly FlutterActivity?

For more info, the platform exception occurs on the line

`StripePayment.paymentRequestWithCardForm(CardFormPaymentRequest())`

**Comment by NickCullen** [comment]
In fact, my suggestion fixes the issue!

Line number 189 in **/gettipsi/**/StripeModule.java

`Activity currentActivity = (Activity) getCurrentActivity();`

I have had to locally clone this repo as I'm in a rush but feel free to apply that fix yourself.

**Comment by jonasbark** [comment]
Could you make a pull request for this? 👍

**Comment by sandeep-at-airlift** [comment]
I hit the same issue as @NickCullen and thought I'd create the PR
