### ISSUE TITLE
Error "Unsupported operation : Platform._operatingSystem" When Running on Flutter Web

### ISSUE THREAD

**Issue by ricky7171** [jonasbark/flutter_stripe_payment#99]
Step to produce error : 
1. Make new flutter project
2. I replace my main.dart with main.dart flutter_stripe_payment (https://github.com/jonasbark/flutter_stripe_payment/tree/master/example/lib)
3. I change min_sdk from 16 to 23 on build.gradle (/android/app/build.gradle)
4. I replace <meta-data> on AndroidManifest.xml (android/app/src/main/AndroidManifest.xml) with this code : 
<meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
5. I replace code on MainActivity.kt (android/app/src/main/kotlin/.../MainActivity.kt) with this code : 
package jonasbark.de.stripepaymentexample

import android.os.Bundle
import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity : FlutterActivity() {

    @Override
    protected override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(this)
    }
}

6. Then, I switch my flutter channel to Master. 
7. Then, I run "flutter run -d chrome"
8. Then I got error like this : 
![stripe web error](https://user-images.githubusercontent.com/56164568/69394279-2b935300-0d0e-11ea-9e7d-68e0c1b3a4bf.png)

Then I tried to find the error on the internet, then I got an answer that the error came from the code:
import darts: io

From there, I suspect that in this package, there is an import dart: io which causes errors when running on the web.

Then I searched on github jonasbark / flutter_stripe_payment, and I found import dart: io in the error_codes.dart file (https://github.com/jonasbark/flutter_stripe_payment/blob/master/lib/src/error_codes.dart)

I suspect that this is the reason why this package cannot be compiled on the web. But I do not understand for sure.

**Comment by jonasbark** [comment]
This plugin does not support Flutter web, see https://github.com/jonasbark/flutter_stripe_payment/issues/95

**Comment by Jacobsjj2** [comment]
Adding initial support should be possible by avoiding calls to Platform.is*. Please see #105
